conforma/policy

policies/examples/attestation_checks.rego, policies/examples/attestation_checks_test.rego
I'm aiming to create a set of useful and tested examples that can
serve as a reference when we do write the real policies.
This example shows how to use some mocked data and write some test
coverage for a more realistic rule.
=> Add an example policy related to attestation data

Makefile, policies/lib/config.rego
So we can conveniently test these rego rules for hacking purposes.
It uses cosign download to avoid needing to provide the public signing
key, which would be needed if we did a cosign verify-attestation.
Also:
- Throw in the dummy policy config so we skip the not useful test,
(which is also what happens in the related task in the
build-definitions repo)
- Pretty up the makefile a little and mention the new tasks in the
help
- Add quay.io/buildah just to make the default attestation pass
the policy check
- Some todo commentary about the repo matching since I realized it
would generally match on organization (in quay.io at least) rather
than a repo. That could be a feature, but it's not described well.
Note:
- The file path data/attestations.json would work the same as …
=> Makefile action for fetching registry attestations

policies/main.rego, policies/main_test.rego, policies/test.rego, policies/test_test.rego
This is the simplest policy for asserting the test stream's output. Two
rules are provided: that there is some test data available and that
all[1] data indicates successful outcome.
Ref. https://issues.redhat.com/browse/HACBS-340
[1]there are more than one test data JSON files, currently at two for
`sanity-inspect-image` and `sanity-label-check` tasks.
=> Policy for asserting test output

policies/test.rego, policies/test_test.rego
With this we can pass the Enterprise Contract checks not only when asserting the whole test data, but also for parts of the test data.
Previously we could set:
data.config.policy.non_blocking_checks: ["test"]
To disregard asserting all test data.
Now we can also disregard asserting parts of the test data, e.g. for `conftest-clair` we can now set:
data.config.policy.non_blocking_checks: ["test:conftest-clair"]
Ref. https://issues.redhat.com/browse/HACBS-360
=> Nested rule unblocking when asserting test data

Makefile, policies/attestation_type.rego, policies/attestation_type_test.rego, policies/main.rego, policies/main_test.rego, policies/not_useful.rego, policies/not_useful_test.rego, policies/step_image_registries.rego, policies/step_image_registries_test.rego, policies/test.rego, policies/test_test.rego
This moves the policy rules to `policies` package so we can generalize over all policies. That is, in `main` we no longer need to call out each policy by name.
The test for main is now a bit more fragile as changes to the policies could fail the test, this is to assert that the output from main hasn't changed in it's shape (say from a set to an array).
=> Refactor to generalize

Makefile
We deliberately dropped the output of `opa test --threshold ...` as when the test coverage target is met `opa` will output a large JSON file with the coverage detail.
If the `make test` fails on the test coverage not being met it fails with this message:
```
...
PASS: 26/26
make: *** [Makefile:28: test] Error 2
```
This could lead to confusion about what actually failed, so with this in such cases the message is now:
```
...
PASS: 26/26
ERROR: Code coverage threshold not met: got 99.35 instead of 100.00
make: *** [Makefile:28: test] Error 2
```
=> Nicer coverage threshold not met message

.github/workflows/pre-merge-ci.yaml, Makefile
Additional check we can make is to run `opa check`, this adds it as a
rule to the Makefile and refactors the GitHub workflow to run the `ci`
rule. There are a few[1] strict checks that are currently enforced.
The difference in running the `ci` rule is that instead of `test`
`test-quiet` is invoked.
[1] https://www.openpolicyagent.org/docs/latest/strict/
=> Run `opa check` in strict mode

Makefile
This is stolen from the Makefile generated by kubebuilder. The `help` rule now runs `awk` over the Makefile and interprets `#@` and `##` comments to determine categories and descriptions of rules. This way we don't need to update the text in the `help` rule and the description of the rule is now inline with the rule itself.
Output now looks like:
```
make help
Usage:
make <target>
General
help             Display this help.
Development
test             Run all tests in verbose mode and check coverage
coverage         Show which lines of rego are not covered by tests
quiet-test       Run all tests in quiet mode and check coverage
live-test        Continuously run tests on changes to any `*.rego` files, `entr` needs to be installed
fmt              Apply default formatting to all rego …
```
=> Nicer `make help` output

policies/examples/time_base_test.rego, policies/examples/time_based.rego, policies/lib/time.rego, policies/lib/time_test.rego, policies/main.rego, policies/main_test.rego
Demonstrates how annotations can be placed in different scopes and how to fetch the effective value of the annotation based on a scoped precedence.
Also includes:
[Different scopes of annotations](https://github.com/hacbs-contract/ec-policies/commit/98af5b0243b07b25f24b0e78c33eb37db4147dd8)
Demonstrates how annotations can be placed in different scopes and how to fetch the effective value of the annotation based on a scoped precedence.
=> Use annotations as the source of effective_on date

Makefile
You pretty much always want to add the fmt and docs changes to your
commit, let's make that easier.
I amended the wrong commit a few times, to decided to add a
confirmation so you have a chance to bail out.
=> Short cuts for committing docs and fmt changes

Makefile, checks/annotations.rego, checks/annotations_test.rego
Adds rules written in Rego to check the output of `opa inspect -a` to
make sure that policies conform to conventions.
First rule added is to check that the required annotations are present.
=> Checks for required annotations in policy files

checks/annotations.rego, docs.tmpl, docs/index.md, policies/attestation_task_bundle.rego, policies/attestation_task_bundle_test.rego, policies/attestation_type.rego, policies/attestation_type_test.rego, policies/lib/string_utils.rego, policies/main.rego, policies/main_test.rego, policies/not_useful.rego, policies/not_useful_test.rego, policies/step_image_registries.rego, policies/step_image_registries_test.rego, policies/test.rego, policies/test_test.rego
Issue: [HACBS-520](https://issues.redhat.com/browse/HACBS-520)
Every existing rule has a default `effective_on` date set to the beginning
of the year 2022. This is an arbitrary date to capture rules that have
already been effective before the introduction of time-based rules.
As per previous design decision, every policy rule should have an
explicit `effective_on` date to better assist the policy rule authors when
introducing a new policy rule.
In addition to the error message, `msg`, and `metadata.code`, a rule
result will also include `metadata.effective_on`. This is meant to
assist users in determining when a blocking issue has been introduced.
So it is automatically reported as warnings by conftest.
Since `metadata.effective_on` is already present in the rules result,
this also aids …
=> Display future failures as conftest warnings

docs/index.adoc, docs/index.md, policy/pipeline/basic.rego, policy/pipeline/main_test.rego, policy/pipeline/required_tasks.rego, policy/pipeline/required_tasks_test.rego
This was added quickly as a potential demo for how pipeline
validation could work.
I'm not sure if matching the taskRef name is a secure approach in
the long term, but it might be a good starting point.
=> Add a 'task must be present' rule for pipelines

Makefile
```
$ make conventions-check
ERROR: Missing annotation(s) custom.failure_msg at policy/release/test.rego:15 ERROR: Missing annotation(s) custom.short_name at policy/release/attestation_type.rego:18
make: *** [Makefile:89: conventions-check] Error 1
```
vs
```
$ make conventions-check
ERROR: Missing annotation(s) custom.failure_msg at policy/release/test.rego:15
ERROR: Missing annotation(s) custom.short_name at policy/release/attestation_type.rego:18
make: *** [Makefile:89: conventions-check] Error 1
```
=> Fix `conventions-check` output

docs/index.adoc, docs/index.md, docsrc/index.adoc.tmpl, docsrc/index.md.tmpl, policy/pipeline/required_tasks.rego, policy/release/step_image_registries.rego
Make it so we don't need custom content in the docs templates each
time we use annotations data in a rule, which causes the required
task refs from the new pipeline rule to appear in the docs where
they didn't before.
=> Refactor annotations data handling for docs

README.md
So it can be more easily found.
=> Link to POLICY_AUTHORING.md from README.md

antora-docs/modules/ROOT/pages/index.adoc, policy/release/attestation_task_bundle.rego
This should get the e2e tests passing again.
=> Add appstudio-tasks to permitted task bundles list

antora-docs/modules/ROOT/pages/index.adoc, policy/release/test.rego, policy/release/test_test.rego
With this we support the "SKIPPED" test result status. The definition of `deny` for test results is changed to not being a "FAILURE" or "ERROR", instead of being "SUCCESS"; and a new `warn` is added for tests with the status of "SKIPPED".
Ref. https://issues.redhat.com/browse/HACBS-740
=> Support "SKIPPED" test result status

antora-docs/modules/ROOT/pages/index.adoc, docsrc/index.adoc.tmpl
Seems that the order of keys in data from `opa inspect` can vary, it is
also unclear if unmarshalling the resulting JSON can lead to it being
reordered due to golang's map hashing algorithm. To achieve
deterministic output in the docs this sorts the data by location: rule
file path and line number of the rule's definition; in the documentation
template.
=> Order OPA inspect data within doc template

antora-docs/modules/ROOT/pages/index.adoc, docsrc/index.adoc.tmpl, policy/release/tasks.rego, policy/release/tasks_test.rego
This adds two policy checks: `tasks_missing` if there are no tasks in the PipelineRun attestation; and `tasks_required` if the required tasks are not present in the PipelineRun attestation.
In addition to custom annotation for `rule_data` in the rule scope, this also allows custom `rule_data` annotation at the package scope that is nested within the rule's short name. In this case this was necessary so that the list of required tasks is not repeated between the test and the rule implementation. This allows us to define `rule_data` for the `tasks_required` rule and the tests in the single location.
Ref. https://issues.redhat.com/browse/HACBS-676
=> Validate required tasks present in attestation

Makefile
We can't have `opa test` load files from `.github` directory, the YAML
files in there will not be of the same schema, so we'll end up with:
```
$ opa test .
1 error occurred during loading: .github/workflows/pre-merge-ci.yaml: merge error
```
This adds `--ignore` to ignore all hidden directories.
=> Ignore hidden files in `opa test`

docs/_config.yml, docs/index.md
This is no longer needed with the Antora setup we have.
=> Removes the unused Jekyll documentation setup

.gitignore, Makefile
Adds two targets to the `Makefile` to build the documentation locally:
`docs-build-local` and to run in preview mode: `docs-preview`, that
rebuilds as the configuration or the documentation changes.
Both need a recent Node.js installation.
=> Local Antora build and preview

.github/workflows/docs.yaml, Makefile, antora-playbook.yml
To prevent checking out the repository twice we can build from local
checkout in all cases (for `docs-render` and `docs-preview` targets).
This both simplifies the rendering and makes it deterministic, as we
didn't specify `--fetch` which would go through the Antora cache and
possibly use an older version of the documentation.
This way we also don't require the GitHub Action to render, and can use
the `docs-render` target from the Makefile, so one less item to
maintain.
=> Render documentation from local source always

antora-docs/modules/ROOT/pages/release_policy.adoc, policy/release/java.rego, policy/release/java_test.rego, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/main_test.rego, policy/release/test_test.rego
Adds a new rule to assert that the `SBOM_JAVA_COMPONENTS_COUNT` result
contains only `redhat` and `rebuilt` counts.
Ref. https://issues.redhat.com/browse/HACBS-931
=> Rule to assert Java dependency provenance

package-lock.json, package.json
Not sure how, why or it this works, just copying it from here:
https://github.com/hacbs-contract/ec-cli/blob/8d7c6ec9e0b640e5a1f75aeae8488037d49c81f5/website/package.json#L14-L16
I also ran npm update to refresh the lock file.
=> Avoid dependabot alert on glob-parent node module

policy/lib/bundles.rego, policy/lib/bundles_test.rego, policy/pipeline/task_bundle.rego, policy/pipeline/task_bundle_test.rego, policy/release/attestation_task_bundle.rego, policy/release/attestation_task_bundle_test.rego
```
Add task bundle rules for pipeline package
Refactored the existing task bundle rules for release package as to
minimize code duplication.
```
```
Add warning when unpinned tekton bundle is used
```
https://issues.redhat.com/browse/HACBS-984
=> Add task bundle rules for pipeline package

antora/docs/modules/ROOT/nav.adoc, antora/docs/modules/ROOT/templates/raw_data.hbs, antora/ec-policies-antora-extension/index.js
The idea is that the UI team could use that to expose the rules and their metadata to users via the web UI.
Do some extra work so that the package information is available in a more convenient place.
=> Provide "raw" data file in docs

policy/lib/bundles.rego, policy/lib/bundles_test.rego, policy/release/java.rego, policy/release/java_test.rego, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/main_test.rego, policy/release/tasks.rego, policy/release/tasks_test.rego, policy/release/test.rego, policy/release/test_test.rego
With this the `TaskRun` results considered by the `test` and `java` policy rules need to be from a `TaskRun` loaded from via a Tekton Bundle, i.e. not defined on the cluster or inline in a `PipelineRun`, and the image reference from which the `Task` was loaded needs to be one from the list of accepted bundles (`acceptable_tekton_bundles.yml`).
The caveat with the `java` policy rules is that there is no policy denial resulting from omission of the result. This is relevant here because the omission of the result could be due to the `TaskRun` result resulting from an inline, cluster or unacceptable bundle.
Ref. https://issues.redhat.com/browse/HACBS-995
=> Check provenance of test and java TaskRun results

policy/release/tasks.rego, policy/release/tasks_test.rego
This is built upon #139, so review that first.
The `sanity-label-check` Task can be parameterized with `POLICY_NAMESPACE` parameter, which can have values `required_checks` and `optional_checks`. When the task is run in the pipeline it is given then name `sanity-label-check` and `sanity-optional-label-check`. Note this is the given name for a `Task` within the `PipelineRun`. We assert the name of the referenced task from the Task Bundle, which in both cases is `sanity-label-check`.
So to distinguish between this two cases in addition to requiring a task by name, this allows to require a task by a parameter and value.
So the required task list now can include:
- `sanity-label-check[POLICY_NAMESPACE=required_checks]`
- `sanity-label-check[POLICY_NAMESPACE=optional_checks]`
This resolves the …
=> Required tasks policy with invocation parameters

policy/release/tasks.rego
The task named add-sbom-and-push does not exist. Instead, the sbom work is done as a step of the corresponding build task, e.g. buildah.
Checking that the SBOM was created will be done in the future as part of https://issues.redhat.com/browse/HACBS-1230
=> Remove unknown required task add-sbom-and-push

.github/workflows/release-antora-extension.yaml, antora/ec-policies-antora-extension/package.json
Caching makes for faster builds, having the engine in the package.json makes it easier to consume and configure the build.
=> Use node version from package.json and cache

policy/release/authorization.rego, policy/release/authorization_test.rego
This updates the authorizations to support a list of repositories and changeIds. Each repo and changeId is compared against the repository and git sha in the attestation.
=> Support a list of authorizations

policy/release/tasks.rego
See https://github.com/redhat-appstudio/build-definitions/pull/216
=> Don't require `sast-go` task

policy/lib/annotations.rego, policy/lib/annotations_test.rego, policy/release/attestation_type.rego
Modify the attestion_type policy rule to better conform with the rego style guide suggested in https://github.com/StyraInc/rego-style-guide
Notable chagnes:
* Use the newer "container ... if" syntax
* Use help function to extract value from annotation
* Use the newer "some ... in" syntax
=> Try new styling format

policy/release/java.rego, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/test.rego
Task results are not required to be a JSON object. This commit changes the data returned by `results_named` to better represent this.
This work is required for https://issues.redhat.com/browse/HACBS-1291
=> Add support for different JSON types of results

policy/lib/include_exclude_rules.rego, policy/lib/include_exclude_rules_test.rego
This commit modifies "collection" to "collections" and now expects an array of strings.
Signed-off-by: Rob Nester <rnester@redhat.com>
=> HACBS-1330 Collections are now arrays

policy/pipeline/required_tasks.rego, policy/pipeline/required_tasks_test.rego, policy/release/tasks.rego, policy/release/tasks_test.rego
The `sbom-json-checks` task emits the standard `HACBS_TEST_OUTPUT` result. So if the SBOM is either missing or invalid, the result will indicate a failure. This should be covered by the existing policies in the `policy.release.test` package. However, we do want to make sure that this check is always performed. For this reason, the task is added to the list of required tasks.
As part of testing, I noticed that I was hitting the issue described in [HACBS-1366](https://issues.redhat.com/browse/HACBS-1366). I decided to fix that issue as well so I could be re-assured the new policy is working as expected. A unit test was added to ensure the previously breaking scenario is covered.
=> Policy rule to assert SBOM was included in the built image

.github/workflows/release-antora-extension.yaml
Seems that setup-node now looks at the lock file in the workspace root and `cache-dependency-path` needs to be provided for it to find the extension's lock file.
=> Add cache-dependency-path for setup-node

data/rule_data.yml, policy/release/base_image_registries.rego, policy/release/base_image_registries_test.rego
This allows someone to re-use the policies but provide a different set of data values to be used by the policy rules. For example, it is possible for someone to specify different allowed registries for base images.
At this point, this is meant for illustration purposes for the spike: https://issues.redhat.com/browse/HACBS-1329
=> Split data from policy rules

Makefile, checks/collections.rego, checks/collections_test.rego
This adds a convention check to make sure that the defined collections are consistent, i.e. they do not reference non-existent rules.
Ref. https://issues.redhat.com/browse/HACBS-1422
=> Validate collection consistency

policy/release/test.rego, policy/release/test_test.rego
Given that the ec cli now passes through both TaskRun and PipelineRun attestation input it considers test results missing when examining the TaskRun attestation input, resulting in the `test_data_missing` error being reported.
This makes sure that `test_data_missing` error is reported only if the examined input is a PipelineRun attestation.
=> Consider missing test results only in PipelineRuns

artifacthub-repo.yml
The config is used to verify ownership of a repo
=> artifact repo config

policy/lib/bundles.rego, policy/lib/bundles_test.rego
The task Tekton bundles produced by the
redhat-appstudio/build-definitions repository used to have a very unique structure. All the task definitions were split into chunks of 10, a bundle would then created for each chunk, finally all bundles would be pushed to the *same* OCI repository. To differentiate between the different chunks, a digit suffix was added to the tag of each bundle. So for the commit "abc", three Tekton bundles would be pushed to the same repo, "abc-1", "abc-2", and "abc-3".
In order to properly determine if an acceptable bundle was being used, the policies had to understand this structure. This was done by dynamically splitting the list of bundles by the tag pattern, so "abc-1" and "bcd-1" were on the same sub-list, but "abc-2" and "bcd-2" were on a separate sub-list. …
=> Remove support for multi-stream bundle repos

policy/release/buildah_build_task.rego, policy/release/buildah_build_task_test.rego
The policy rule dockerfile_param_not_included is only meant to be executed when there's a pipeline run attestation.
=> Ignore buildah policy for non pipeline run att

policy/lib/result_helper.rego, policy/lib/result_helper_test.rego, policy/pipeline/basic_test.rego, policy/pipeline/required_tasks_test.rego, policy/pipeline/task_bundle_test.rego, policy/release/attestation_task_bundle_test.rego, policy/release/attestation_type_test.rego, policy/release/authorization_test.rego, policy/release/base_image_registries_test.rego, policy/release/buildah_build_task_test.rego, policy/release/hermetic_build_task_test.rego, policy/release/java_test.rego, policy/release/not_useful_test.rego, policy/release/slsa_build_build_service_test.rego, policy/release/slsa_build_scripted_build_test.rego, policy/release/slsa_provenance_available_test.rego, policy/release/slsa_source_version_controlled_test.rego, policy/release/step_image_registries_test.rego, policy/release/tasks_test.rego, policy/release/test_test.rego
Any violation code will now contain the package name followed by the policy rule short name. This helps users more easily determine what should be used in an include/exclude statement.
It also paves the way for moving the include/exclude logic out of rego and into the ec-cli, see https://issues.redhat.com/browse/HACBS-1303
=> Display package name in violation code

data/rule_data.yml, policy/release/test.rego, policy/release/test_test.rego
[ADR-0008](https://github.com/redhat-appstudio/book/pull/24) defines five different test result status types -- `SUCCESS`, `FAILURE`, `WARNING`, `SKIPPED` and `ERROR`. There was no policy defined for handling the `WARNING` result type.
Signed-off-by: arewm <arewm@users.noreply.github.com>
=> Add WARNING test result

.github/workflows/pre-merge-ci.yaml, .gitignore, Makefile, hack/simplecov.rego
Adds a Make target `coverage-report` that generates `coverage.json` in SimpleCov format using `hack/simplecov.rego` sourced from[1] and uploads it in pre-merge-ci workflow to codecov.io.
[1] https://github.com/open-policy-agent/contrib/tree/main/simplecov
=> Upload code coverage to codecov.io

antora/docs/acceptable_tekton_bundles.yml, antora/docs/modules/ROOT/attachments/acceptable_tekton_bundles.yml, antora/docs/modules/ROOT/attachments/rule_data.yml, antora/docs/modules/ROOT/templates/policy_configuration.hbs, antora/docs/rule_data.yml, policy/pipeline/task_bundle.rego, policy/release/attestation_task_bundle.rego
This way we can capture the version that was present at the build time, and allow for different versions of the documentation to point to different files or files with varying content.
Ref. https://issues.redhat.com/browse/HACBS-1574
=> Use attachments in documentation

.github/workflows/push-bundles.yaml
Otherwise `git log -n1 -- some/dir` always shows the top commit which breaks the test to decide if a bundle push is required.
Also remove an obsolete todo comment.
=> Fetch full git history in push bundle workflow

antora/ec-policies-antora-extension/index.js
Let's not require that `acceptable_tekton_bundles.yml` is placed in the root of the Antora site content, as with the latest change it was placed in `modules/ROOT/attachments/acceptable_tekton_bundles.yml`. Fixes the docs build:
```
[09:26:53.558] FATAL (antora): Unable to find acceptable bundles file: (/home/runner/work/hacbs-contract.github.io/hacbs-contract.github.io/node_modules/@hacbs-contract/ec-policies-antora-extension/index.js)
```
=> Fix regex to find `acceptable_tekton_bundles.yml`

data/rule_data.yml, policy/lib/rule_data.rego
It's a long story, but this is a hacky but effective way to ensure a bundle push will be triggered with image digests that are new and unique. If we ever need to do it again we can bump the number.
(Previously I've added some random comment or whitespace change, but I didn't want to keep doing that.)
Related to https://issues.redhat.com/browse/HACBS-1603
=> Force bundle push with fresh bundle digest

.github/workflows/push-bundles.yaml, data/rule_data.yml, hack/update-bundles.sh, policy/lib/rule_data.rego
In update-bundles.sh optionally add a timestamp so that the bundle content and hence its digest is always different to all previous bundles when attempting to push a bundle.
It's a workaound to avoid the error described in PROJQUAY-4977 (...which we seem to be hitting sometimes even when the bundle digest should be new, so this patch might not actually be a solution...)
Also:
- Add a dry run option so you can more easily test the logic in the script without actually doing a real push.
- Add the new env var to the github workflow definition.
- Remove the "uniqueness bump number" used previously.
=> Ensure policy bundle always have a unique digest

.github/workflows/push-bundles.yaml
Sometimes, such as when a previous bundle push failed for some reason, you might want to trigger a bundle push manually.
=> Allow manual trigger of bundle push

policy/lib/array_helpers.rego, policy/lib/array_helpers_test.rego, policy/lib/tekton/task.rego, policy/lib/time.rego, policy/lib/time_test.rego
[Add sort_by and rank functions](https://github.com/hacbs-contract/ec-policies/commit/2bba5dea9bdc24845d08ca173b0c1d72670d32d6)
Adds `lib.arrays` package with `sort_by` and `rank` functions.
[Add time.newest function](https://github.com/hacbs-contract/ec-policies/commit/bfb9cdbf689c6bcb960608fddc17fdea70662dda)
[Use the newest task instead of first by order](https://github.com/hacbs-contract/ec-policies/commit/7de9ca9806b5e8bb9846e4df0af01b49191b19c5)
Ref. https://issues.redhat.com/browse/HACBS-1507
=> Don't rely on the time-descending order of the "required-tasks" data

antora/ec-policies-antora-extension/index.js
We can leave the `origin` as `undefined`, otherwise Antora when logging tries to deconstruct the `origin` as an object which is not possible for a fixed string `"dynamic"`.
The intent was to not show the `Edit this page` link for generated content, leaving `origin` as `undefined` accomplishes the same.
=> Remove `origin: "dynamic"` from catalog entries

antora/ec-policies-antora-extension/index.js, antora/ec-policies-antora-extension/package-lock.json
Multiple promises end up creating multiple event listeners which might not all get unregistered on node process exit. This uses the `inspect` function from opa-inspect-js that accepts multiple Vynl file objects so a single promise ends up being used.
=> Use single promise with opa-inspect-js

antora/docs/modules/ROOT/templates/_rules.hbs, antora/ec-policies-antora-extension/index.js
Prepend parts of the package, namely type (release, pipeline) and package name to the rule short name and form an `anchor` property that is used to make sure that the ids/anchors point to unique values.
=> Make rule anchors unique

README.md
verify-enterprise-contract.yaml has been moved out from build-definition repo to ec-cli repo.
=> chore: update the redirect url of verify enterprise contract task definition in README.md

data/acceptable_tekton_bundles.yml
This bundled was first created 21 days ago, and was meant to be included in the PR:
https://github.com/hacbs-contract/ec-policies/pull/229
Due to timing issues, when a PR from build-definitions includes more than one PR, only the changes from the last one in the list is retained.
The bundle was updated today, and again hit the same issue on this PR: https://github.com/hacbs-contract/ec-policies/pull/288
=> Add fbc-validation to the acceptable bundles list

antora/docs/modules/ROOT/templates/_rules.hbs, antora/ec-policies-antora-extension/index.js
Removed rule annotation processing code from the Antora extention.
Signed-off-by: Rob Nester <rnester@redhat.com>
=> REMOVE rule annotation processing code for docs

.github/workflows/docs.yaml
This extends the docs workflow to trigger the documentation build in redhat-appstudio/docs.stonesoup.io and
hacbs-contract/hacbs-contract.github.io repositories.
=> Trigger docs build for AppStudio docs

policy/lib/tekton/pipeline.rego, policy/lib/tekton/task.rego, policy/pipeline/required_tasks.rego, policy/pipeline/required_tasks_test.rego
update required pipeline tasks to look for tasks in `pipeline-required-tasks` key in acceptable bundles. If not found, look at the `required-tasks`.
=> update required pipeline tasks to use pipeline-required-tasks from acceptable bundles

hack/update-bundles.sh
If two commits are merged in this repo within a given time window, and one updates only data while the other updates only policy, then one of those may not land on the infra-deployments PR.
This commit fixes the issue by always passing all the bundle references to the pr-infra-deployments script.
=> Ensure infra-deployments PR uses latest bundles

policy/release/artifacthub-pkg.yml
There are three install instructions that are showing up on the same line. This separates them to make them more readable.
=> make install command on a newline

antora/docs/modules/ROOT/templates/_rules.hbs
Now that we show the code that way in the ec output it's much better to do the same in the docs.
=> Show code as `package_name.rule_name` in docs

antora/docs/modules/ROOT/pages/authoring.adoc, antora/docs/modules/ROOT/templates/policy_configuration.hbs, antora/docs/modules/ROOT/templates/release_policy.hbs, antora/ec-policies-antora-extension/index.js, antora/ec-policies-antora-extension/package-lock.json, policy/release/collection/minimal.rego, policy/release/collection/slsa1.rego, policy/release/collection/slsa2.rego, policy/release/collection/slsa3.rego
Introduces empty Rego packages to document the rule collections, these are in `policy.release.<collection>` package, but to reduce the release policy directory, placed in `policy/release/collection` directory.
The rule collection table has been moved to Release Policy documentation.
Ref. https://issues.redhat.com/browse/HACBS-1749
=> Rule collection improvements

policy/task/kind.rego, policy/task/kind_test.rego
This is to get started on a policy for task definitions. Starting with a basic `kind` check.
=> initial policy for task definitions

policy/release/java.rego, policy/release/java_test.rego
This was missed in https://github.com/hacbs-contract/ec-policies/pull/297
The removed test didn't do anything. It produced no violations because the expected result was provided.
=> Update docs for java policy with acceptable tasks

policy/pipeline/basic.rego, policy/pipeline/required_tasks.rego, policy/pipeline/task_bundle.rego, policy/release/attestation_task_bundle.rego, policy/release/attestation_type.rego, policy/release/authorization.rego, policy/release/base_image_registries.rego, policy/release/buildah_build_task.rego, policy/release/collection/minimal.rego, policy/release/collection/slsa1.rego, policy/release/collection/slsa2.rego, policy/release/collection/slsa3.rego, policy/release/hermetic_build_task.rego, policy/release/java.rego, policy/release/slsa_build_build_service.rego, policy/release/slsa_build_scripted_build.rego, policy/release/slsa_provenance_available.rego, policy/release/slsa_source_version_controlled.rego, policy/release/step_image_registries.rego, policy/release/tasks.rego, policy/release/test.rego, policy/task/kind.rego
It's probably not super important, but it seems nicer to do it this way consistently, and it might make a difference if we do decide to render a text formatted version of the ec output.
=> Less hard line breaks in rule descriptions

antora/docs/modules/ROOT/nav.adoc, antora/docs/modules/ROOT/partials/pipeline_policy_nav.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, antora/docs/modules/ROOT/templates/_rule_links.hbs, antora/docs/modules/ROOT/templates/acceptable_bundles.hbs, antora/docs/modules/ROOT/templates/release_policy.hbs, antora/ec-policies-antora-extension/index.js
Updated navigation for release_policy and pipeline_policy pages as both had grown to contain large amounts of data. Navigation not benefits from fold out navigation in the side bar.
=> Update release_policy and pipeline_policy page nav

hack/update-bundles.sh, hack/update-infra-deployments.sh
This adds the image source revision, `org.opencontainers.image.revision` annotation to the Rego OCI bundle's manifest and uses it to deduce the alternate tag for the `latest` tag of an image when updating the resources in infra-deployments.
We need to keep the source revision (git commit id) within the bundle because not all commits end up pushing an updated bundle. So when we run the update of infra-deployment resources we do not know which commit id-based tag corresponds to the `latest` tag of the Rego OCI bundle we wish to update to.
An alternative to list all tags, fetch manifests and compare those with the `latest` tag is overly expensive (by number of requests) and requires authentication against quay.io to fetch a manifest by tag.
Ref. https://issues.redhat.com/browse/HACBS-1820
=> Use image source revision to deduce tag

antora/docs/modules/ROOT/partials/release_policy_nav.adoc
Seems more appropriate to name this "Release Rules" than "Release Annotations".
=> Heading change

.github/workflows/push-bundles.yaml
As far as I can see this is no longer used.
=> Removes the `DEPLOY_KEY` secret

data/rule_data.yml, policy/lib/rule_data.rego
Make it a little easier for users to know there are some other rule
data keys that they could override if they want to.
The initial motivation was to make it easier for users to be aware
of the two rule data keys related to the cve policy, since
customizing those is a thing that users might want to do. This is
documented in the rule itself, but I figure there's no harm in
making it discoverable in other ways.
Also set the default value of warn_cve_security_levels explicitly to
an empty list. It makes no functional difference, but it makes it
easier for someone reading the code to understand what is going on.
(This does bring up the question of why some keys have default
values in rule_data.rego and others don't, but let's consider that
later.)
=> Mention the built in defaults in rule data yaml

hack/update-infra-deployments.sh
The latest conftest update changes how the urls are split up and the https:// protocol in oci urls doesn't work any more.
=> Remove https from oci urls in automated pr

policy/release/test.rego
How to skip tests is documented in the docs under configuration
=> remove reference to non_blocking

policy/lib/rule_data.rego, policy/lib/rule_data_test.rego
The plan is that EC will create a data file using data found in the ECP CR. This provides a convenient way for a user to specify some custom data without needing to create a data source.
JIRA: HACBS-2042
=> Add one more higher precedence rule data key

antora/ec-policies-antora-extension/index.js
The `task_policy_nav.adoc` and `build_task_policy_nav.adoc` both end with `task_policy_nav.adoc`. This makes the template matching match from the path separator (`/`) to make the template matching exact.
Solves:
```
[07:53:03.996] WARN (asciidoctor): skipping reference to missing attribute: anchor
file: antora/docs/modules/ROOT/nav.adoc
source: https://github.com/enterprise-contract/ec-policies.git (branch: main | start path: antora/docs)
[07:53:04.000] WARN (asciidoctor): skipping reference to missing attribute: title
file: antora/docs/modules/ROOT/nav.adoc
source: https://github.com/enterprise-contract/ec-policies.git (branch: main | start path: antora/docs)
```
=> Make sure the partial template is matched

policy/pipeline/task_bundle.rego, policy/release/attestation_task_bundle.rego, policy/release/tasks.rego, policy/release/test.rego
Some policy rules include asciidoc links in their description. The docs building process replaces them with the correct link markup. However, the description is used in other contexts which are agnostic to our building process, e.g. `ec validate image --info`.
In https://issues.redhat.com/browse/HACBS-2102, a change to the ec-cli is being made to remove such asciidoc markup and leave only the text behind.
This change updates the wording of the description to still make sense if a given part of the text is not a link.
This also removes some outdated references to acceptable bundles. (Not all policy rules that check tasks require them to come from acceptable bundles.)
=> Update description to not require a link

policy/release/attestation_task_bundle.rego, policy/release/attestation_task_bundle_test.rego, policy/release/attestation_type.rego, policy/release/attestation_type_test.rego, policy/release/base_image_registries.rego, policy/release/base_image_registries_test.rego, policy/release/buildah_build_task.rego, policy/release/buildah_build_task_test.rego, policy/release/cve.rego, policy/release/cve_test.rego, policy/release/hermetic_build_task.rego, policy/release/hermetic_build_task_test.rego, policy/release/java.rego, policy/release/java_test.rego, policy/release/provenance_materials.rego, policy/release/provenance_materials_test.rego, policy/release/slsa_build_build_service.rego, policy/release/slsa_build_build_service_test.rego, policy/release/slsa_build_scripted_build.rego, policy/release/slsa_build_scripted_build_test.rego, policy/release/slsa_provenance_available.rego, policy/release/slsa_provenance_available_test.rego, policy/release/slsa_source_version_controlled.rego, policy/release/slsa_source_version_controlled_test.rego, policy/release/step_image_registries.rego, policy/release/step_image_registries_test.rego, policy/release/tasks.rego, policy/release/tasks_test.rego, policy/release/test.rego, policy/release/test_test.rego
The idea is that the title and name should describe what is being checked, rather than describe the failure condition. This means the title text makes more sense when used in the UI if the rule is passing or if the rule is failing.
I'm also changing the short name for consistency, even though the short name is not as exposed via the web UI.
JIRA: [HACBS-2095](https://issues.redhat.com/browse/HACBS-2095)
=> Revise rule titles and short names

policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/test_test.rego
Fall back to the old name if required to make the transition more smooth. Eventually we can remove the deprecated name entirely.
JIRA: [HACBS-2159](https://issues.redhat.com/browse/HACBS-2159)
=> Support new TEST_OUTPUT task result

data/rule_data.yml
This removes quay.io/containerbuildsystem/cachi2 from `allowed_step_image_registry_prefixes`.
=> Removes quay.io/containerbuildsystem/cachi2

antora/ec-policies-antora-extension/index.js
This allows us to have `.rego` files for the purpose of generating data
for the documentation in any component.
Also includes [Allow package names with more than 3 parts](https://github.com/enterprise-contract/ec-policies/commit/3c3d00a02226f2cccac9e483ba79d76e8ea4cae8)
Ref. https://issues.redhat.com/browse/HACBS-2162
=> Allow Rego files to originate from any content

policy/release/attestation_task_bundle.rego, policy/release/test.rego
For consistency as most of the rules already use this syntax.
=> Use new `contains ... if` syntax

policy/pipeline/required_tasks.rego, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego
The result has been deprecated and now is removed.
=> remove HACBS_TEST_OUTPUT result

README.md, antora/docs/modules/ROOT/pages/policy_bundles.adoc
Some of the links were broken or pointing to stale locations.
=> Update doc links

.github/workflows/enable-auto-merge.yaml, .github/workflows/pre-merge-ci.yaml
It is recommended to set a read-level permission at the top level of the workflow. Then, if needed, add write-level permission at the job level. See https://github.com/orgs/enterprise-contract/security/risk
=> Set top-level token permissions on workflows

policy/release/buildah_build_task.rego, policy/release/buildah_build_task_test.rego
Given that some projects might include the buildah task more than once, this opts to allow it and enforce the existing rules on all of them.
The message for missing parameters to the buildah task was modified to include all the tasks that miss their parameters.
The message for using non-local Dockerfile was not changed.
Ref. https://issues.redhat.com/browse/HACBS-2280
=> Allow more than one buildah task

.github/workflows/enable-auto-merge.yaml
The permission required is `contents` and not `pull-requests`.
=> Fix auto-merge permission

policy/release/github_certificate.rego, policy/release/github_certificate_test.rego
https://issues.redhat.com/browse/HACBS-2083
To try it out, create the policy below.
`policy.yaml`
```yaml
sources:
- name: Default
policy:
- github.com/lcarva/ec-policies//policy/lib?ref=HACBS-2083
- github.com/lcarva/ec-policies//policy/release?ref=HACBS-2083
data:
- github.com/lcarva/ec-policies//data?ref=HACBS-2083
ruleData:
allowed_gh_workflow_repos: [lcarva/festoji]
allowed_gh_workflow_refs: [refs/heads/master]
allowed_gh_workflow_names: [Package]
allowed_gh_workflow_triggers: [push]
configuration:
include:
- '@slsa1'
- '@slsa2'
- '@slsa3'
- github_certificate
```
And run ec against an image built on GitHub:
```bash
EC_EXPERIMENTAL=1 ec validate image \
--policy policy.yaml \
--image quay.io/lucarval/festoji:latest \
--output yaml \
--certificate-identity-regexp …
```
=> Add policies to validate GitHub certificates

policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego
I could not create a unit test that would fail without `json.is_valid`, which is odd. I did test this with acceptance tests on https://github.com/enterprise-contract/ec-cli/pull/801 and it did help with that.
=> Check if provided string is a valid JSON

data/acceptable_tekton_bundles.yml, hack/check-acceptable-tekton-bundles.sh
Introduce a new script, `hack/check-acceptable-tekton-bundles.sh`, to check if the latest acceptable bundle records match the latest images in the registry.
The script generated most of the changes in `data/acceptable_tekton_bundles.yml`.
The sast-go and sast-java-sec-check tasks had a change that caused their definition to be equal to one of its previous versions. Because of this `ec track bundle` did not re-add entries for those bundles, as it is expected. The issue is that in this case, this behavior doesn't make sense as we want the old digest to be treated as the most up-to-date task definition. I manually fixed up those entries. `ec track bundle` should be smarter about this. This will be done in: https://issues.redhat.com/browse/HACBS-2394
=> Fixup acceptable bundles

antora/docs/modules/ROOT/templates/_rules.hbs, antora/ec-policies-antora-extension/index.js
This commit fixes source links for builtin rule collection entries. These source links now point to the correct locations within the ec-cli repository.
=> HACBS-2319 update source link for builtin rule set

policy/lib/image.rego, policy/lib/image_test.rego, policy/release/olm.rego, policy/release/olm_test.rego
Given the content of the OLM bundle image manifest files in input and the presence of the `operators.operatorframework.io.bundle.manifests.v1` label on the image this checks if all the references mentioned in the Python checker[1] are pinned, i.e. they contain the digest.
Ref. https://issues.redhat.com/browse/HACBS-2379
[1] https://github.com/containerbuildsystem/operator-manifest#pull-specifications
=> Check OLM bundle image's manifests has pinned refs

policy/release/attestation_task_bundle_test.rego, policy/release/attestation_type.rego, policy/release/attestation_type_test.rego, policy/release/buildah_build_task_test.rego, policy/release/external_parameters_test.rego, policy/release/hermetic_build_task_test.rego, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/provenance_materials_test.rego, policy/release/slsa_build_build_service_test.rego, policy/release/slsa_build_scripted_build_test.rego, policy/release/slsa_provenance_available_test.rego, policy/release/slsa_source_version_controlled_test.rego, policy/release/step_image_registries_test.rego, policy/release/tasks_test.rego, policy/release/test_test.rego
This change allows policy rules to be applied to either `input.attestations[].statement` or `input.attestations[]`. The first having higher precedence. At some point in the future, we'll drop support for the second. This is deferred to allow users to update the ec-cli version being used.
https://issues.redhat.com/browse/HACBS-2423
=> Adopt the new input format for attestations

policy/lib/rule_data.rego, policy/release/slsa_source_correlated.rego, policy/release/slsa_source_correlated_test.rego
Given the attested source code reference and the source image code reference this check will make sure of their equality.
A warning is issued for source image data not including the source reference.
A failure will be issued if no source reference is present in the materials section or if the materials does not match the expected image source reference for SLSA Provenance v0.2.
Similarly, a failure will be issued if no source reference is present in the resolvedDependencies or if the resolvedDependencies does not match the expected image source reference for SLSA Provenance v1.0.
Ref. https://issues.redhat.com/browse/HACBS-2247
=> SLSA source correlation check

policy/lib/tekton/task.rego, policy/lib/tekton/task_test.rego, policy/release/buildah_build_task.rego, policy/release/buildah_build_task_test.rego, policy/release/lib/attestations.rego
This modifies the task library to handle tasks from the resolvedDepencies list in a slsav1 attestation.
This ONLY updates the task library and the `buildah_task` policy. More policies need to be updated, but I'm breaking them up into separate PRs to reduce the size.
https://issues.redhat.com/browse/HACBS-2246
=> Update tasks operations so they support slsav1 attestations.

hack/update-infra-deployments.sh
https://issues.redhat.com/browse/HACBS-2556
This commit changes the update-infra-deployments script to only update the policy refs, and not the policy data refs. The policy data used is now established by a different repository,
https://github.com/release-engineering/rhtap-ec-policy.
=> Stop updating policy data refs in RHTAP

policy/release/step_image_registries.rego, policy/release/step_image_registries_test.rego
Starting with version 0.17, Tekton Chains adds the `oci://` prefix to the image references for each task step in the SLSA Provenance.
This change modifies the step_image_registries policies to take this into account.
Ref: RHTAPBUGS-857
This also removes step_image_registries from every collection as we know it is currently broken.
Ref: HACBS-1972
=> Fix and disable step_image_registires

.regal/config.yaml, policy/lib/refs.rego, policy/lib/refs_test.rego, policy/lib/tekton/task.rego, policy/lib/tekton/task_test.rego, policy/release/attestation_task_bundle.rego, policy/release/attestation_task_bundle_test.rego, policy/release/base_image_registries_test.rego, policy/release/buildah_build_task_test.rego, policy/release/cve_test.rego, policy/release/external_parameters.rego, policy/release/java_test.rego, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/step_image_registries.rego, policy/release/step_image_registries_test.rego, policy/release/tasks.rego, policy/release/tasks_test.rego, policy/release/test_test.rego
Refactor all policies that verify an attestation to work with slsav1.0.
- **IMPORTANT**: The task information here is pulled from the `content` field in `resolvedDependencies`. It is the `taskRun` that is stored there.
- This mostly changes libraries to support accessing v0.2 and v1.0 attestations and updating the policy tests to support v1.0.
- Update regal lint to warn on line-length too long. `opa fmt` in many cases is ok with a line-length that `regal lint` is not. So there is a conflict between the two.
https://issues.redhat.com/browse/HACBS-2303
=> slsav1.0 refactor

policy/lib/rule_data.rego, policy/release/cve.rego, policy/release/cve_test.rego
Actually there's no functional change needed for EC to support the new CVE severity, but we mention in the documentation and commentary what the expected value for CVE severity are, so this patch updates that.
Additionally I added 'unknown' to the dummy data in the tests, and added some test coverage so it includes some output for the 'unknown' results. It's also not really needed, but I think it helps communicate the intention for future readers of the code.
Resolves: https://issues.redhat.com/browse/EC-36
=> Mention the 'unknown' CVE severity in descriptions

policy/release/slsa_source_correlated.rego, policy/release/slsa_source_correlated_test.rego
The code assumed if `input.image.source` was present that the data structure would always contain `url` and `revision` properties. Those might be omitted as they're user-controlled inputs, e.g. from the ApplicationSnapshot.
If those properties were omitted then the helper function `_expected_sources` would return empty set as it would try to operate on undefined data, and iterating over an empty set would lead to no checks being performed.
This uses `object.get` instead of direct access to return a default value if the properties are missing, so that the set should be populated and the checks should fail to match.
ref: https://issues.redhat.com/browse/RHTAPBUGS-883
=> Handle partial input.image.source data

policy/lib/bundles.rego, policy/pipeline/task_bundle_test.rego, policy/release/attestation_task_bundle_test.rego
The attestation_task_bundle.task_ref_bundles_acceptable check should produce a failure if the task bundle reference is not found at all in the available `data.task-bundles` data. Previously it was only failing if the repo was present in data.task-bundles and the task's digest wasn't in the list.
Also some extra test coverage is added to exercise the different failure conditions.
Resolves: https://issues.redhat.com/browse/EC-206
=> Ensure unknown tasks fail acceptable bundle checks

.github/workflows/push-bundles.yaml, hack/update-bundles.sh
This makes it possible to run the script against a local registry, or any registry really, which is really useful for development. For example:
```
$ docker run -it -d -p 5000:5000 --restart=always --name registry registry:2
$ REPO_PREFIX=localhost:5000/blah/ ./hack/update-bundles.sh
```
=> Support local registries in update-bundles.sh

policy/pipeline/required_tasks.rego, policy/pipeline/required_tasks_test.rego, policy/release/tasks.rego, policy/release/tasks_test.rego
This adds support for the notion of _one of_ required tasks from the required tasks list.
For example, given required tasks data as:
```yaml
- A
- [B, C, D]
- E
```
Tasks "A", at least one of "B", "C" or "D", and "E" are required.
=> Support _one of_ for required tasks

policy/lib/rule_data.rego, policy/release/test.rego, policy/release/test_test.rego
Some tests are required to be executed, but their results do not have to be successful. They are meant to inform the user that their results need some attention, but they are non-blocking. An example of such test is a certain code scanner which may produce a high number of false positives. These tests are referred to as informative.
This commit modifies the `test` package to more easily support these types of tests.
Also, since `test.no_skipped_tests` has been modified to emit a violation instead of a warning, an effective date to a month from now has been added. This should allow users to gradually address any issues before they become blocking.
Ref: EC-224
=> Add support for informative tests

policy/lib/tekton/pipeline.rego, policy/lib/tekton/pipeline_test.rego
When computing the key to select the set of required tasks we look at the built task's or the pipeline label. Given that the build task for the FBC and the Docker builds are the same, i.e. have the same label. We cannot rely on the task's label, instead we this uses the image label `operators.operatorframework.io.index.configs.v1` to classify a attestation as being an attestation of a FBC image, and subsequently select the set of required tasks for the `fbc` pipeline.
reference: EC-85
=> Do not rely on build task label for FBC images

policy/lib/tekton/pipeline.rego, policy/lib/tekton/task.rego, policy/lib/tekton/task_test.rego, policy/release/hermetic_build_task.rego, policy/release/hermetic_build_task_test.rego, policy/release/provenance_materials.rego, policy/release/provenance_materials_test.rego, policy/release/slsa_build_scripted_build.rego, policy/release/slsa_build_scripted_build_test.rego
This allows more than one git-clone and build task in the pipeline. The constraints in the rules must now match all instances of those, e.g. all build tasks must contain steps, and all git-clone tasks must fetch from the expected repository and revision.
I'm aware that the test coverage for pipelines with more than one of those tasks is non existent. I wanted to put something up for review so we can determine if this is the approach we want to take.
reference: EC-277
=> Support more than one git-clone and build task

go.mod, go.sum, hack/update-bundles.sh, tools.go
The previous approach of using `conftest push` does not work now that EC provides custom rego functions. We could wrap the `conftest` command in EC CLI, like we did for OPA via `ec opa`. However, that is a bit heavy handed.
The OPA docs[1] suggest using `opa bundle` to generate a tarball with the compiled policy rules. Then, use `oras push` to upload the tarball to an OCI registry.
The problem with the approach above is that when the OCI image containing the policy rules is fetched, the output is a tarball instead of the expected rego files. This causes conftest to not see the policy rules. I considered adding support in the EC CLI to handle this use case by simply expanding any tarballs that may have been fetched. But... this means older version of the EC CLI won't be able to consume the …
=> Use oras to build OPA bundles

policy/beta/packages.rego, policy/beta/packages_test.rego, policy/release/attestation_type.rego, policy/release/attestation_type_test.rego, policy/release/base_image_registries.rego, policy/release/base_image_registries_test.rego, policy/release/collection/policy_data.rego, policy/release/cve.rego, policy/release/cve_test.rego, policy/release/external_parameters.rego, policy/release/external_parameters_test.rego, policy/release/github_certificate.rego, policy/release/github_certificate_test.rego, policy/release/java.rego, policy/release/java_test.rego, policy/release/labels.rego, policy/release/labels_test.rego, policy/release/schedule.rego, policy/release/schedule_test.rego, policy/release/slsa_build_build_service.rego, policy/release/slsa_build_build_service_test.rego, policy/release/slsa_provenance_available.rego, policy/release/slsa_provenance_available_test.rego, policy/release/slsa_source_correlated.rego, policy/release/slsa_source_correlated_test.rego, policy/release/step_image_registries.rego, policy/release/step_image_registries_test.rego, policy/release/test.rego, policy/release/test_test.rego
This commit enhances the validation performed on rule data. It defines a JSON Schema for each value and provides a policy rules to execute them.
Ref: EC-132
=> Add validation to rule data

policy/lib/bundles.rego, policy/lib/bundles_test.rego
This prevents policy rules from incorrectly not evaluating due to missing data.
=> Set default value for missing task-bundles

policy/lib/tekton/task.rego, policy/lib/tekton/task_test.rego, policy/release/attestation_task_bundle.rego, policy/release/attestation_task_bundle_test.rego, policy/release/buildah_build_task.rego, policy/release/buildah_build_task_test.rego, policy/release/lib/attestations_test.rego, policy/release/step_image_registries.rego, policy/release/tasks.rego, policy/release/tasks_test.rego
The taskRef name can be excluded if a task is defined inline, but the pipeline task name is always required.
This change only affects the message on a failed rule.
https://issues.redhat.com/browse/RHTAPBUGS-1076
=> Switch to using the pipeline task name instead of the taskRef name

policy/lib/bundles.rego, policy/pipeline/task_bundle_test.rego, policy/release/attestation_task_bundle_test.rego
Currently the acceptable bundles can hold for the same image repository multiple records with the same digest, they would also have the same tag but their effective_on would differ. This would cause the rule to report that the task bundle used is out of date as it would find two records one of which could be newer than the other.
reference: EC-316
=> Handle duplicate acceptable bundle records

hack/update-bundles.sh
We no longer have one, and attempting to push causes failures[1]
[1] https://github.com/enterprise-contract/ec-policies/actions/runs/7448036295/job/20261519761
=> Don't publish `beta` package

policy/release/slsa_build_scripted_build.rego, policy/release/slsa_build_scripted_build_test.rego
EC CLI will set the `input.image.ref` to the image reference, so the digest for comparison needs to be parsed from that string. Note that the digest when parsed, if not present in the image reference will be set to `""`.
=> Use image digest parsed from the reference

policy/lib/bundles.rego, policy/lib/bundles_test.rego, policy/pipeline/required_tasks.rego, policy/pipeline/required_tasks_test.rego, policy/release/tasks.rego, policy/release/tasks_test.rego
Adds an additional check that a record must exist for a bundle the required task originates from. Meaning that the task is from an acceptable bundle.
reference: EC-254
=> Required task must be from acceptable bundle

policy/release/slsa_build_scripted_build.rego, policy/release/slsa_build_scripted_build_test.rego
The function `slsa_build_scripted_build.trusted_build_task_error` could produce more than one result if more than one `build_task_bundles` is untrusted. For example when multiple tasks have the same, expected, `IMAGE_DIGEST` result or if multiple tasks are in the same untrusted bundle as the build task.
This changes the function to operate on tasks instead of bundles and to concatenate any untrusted build task names, so when there are more than one tasks with the expected `IMAGE_DIGEST` result -- a single error message is returned.
This causes:
```
Error: 1 error occurred:
* error validating image quay.io/redhat-appstudio-qe/enterprise-contract-tests:e2e-test-unpinned-task-bundle of component ec-cli: query rule: check: query rule: evaluating policy: …
```
=> Fix function producing multiple outputs

policy/lib/refs.rego, policy/lib/refs_test.rego, policy/release/tasks.rego, policy/release/tasks_test.rego
Ref: EC-257
This change adds a new attribute to the result returned by the
`task_ref` helper function, `pinned`. This indicates whether or not the
an immuntable reference is used.
For example, a git commit ID when using the git resolver is considered a
pinned reference, while a branch name is not.
A previous approach was to introduce a new helper method, e.g.
`is_pinned`. However, the a couple of things became obvious:
* The `task_ref` helper function already has the needed context, e.g.
it knows that it's dealing with a git reference, so it can check if
that's a git commit ID or a branch name.
* Being pinned is a property of the Task reference. It makes sense for
the representation of the Task reference (what `task_ref` returns) to
include this information.
As part of this, I also …
=> Enforce pinning for additional types of Task refs

policy/lib/bundles.rego, policy/lib/bundles_test.rego, policy/pipeline/task_bundle_test.rego, policy/release/attestation_task_bundle_test.rego
The list of acceptable bundles is time based. The presence of a record is not a sufficient indicator for it being valid. As time goes on and the effective_on date of records is reached, older entries fall off the list. Using those records is akin to using a record that is not on the list at all.
This commit introduces a helper function to prune old records from the list before the list is consumed. This consolidates the decision of which records should be ignored in a single place.
This fixes the related bug by ensuring stale records are used consistently across the code base.
It also removes/modifies certain tests which were asserting incorrect behavior.
Ref: RHTAPBUGS-1099
=> Consolidate pruning of stale acceptable bundles

policy/lib/bundles.rego
This commit changes the implementation of bundles.rego to avoid double negatives, e.g. `not _is_unacceptable`. Instead, the logic is implemented in the positive, i.e. `_is_acceptable. This makes the other functions that rely on this a little bit easier to read.
Resolves: #858
=> Minor simplification of bundles.is_acceptable

policy/task/step_image_registries.rego
Collections are not properly supported in the `task` namespace, see https://github.com/enterprise-contract/ec-policies/issues/872
=> Remove collections from step image registries

example/data/trusted_tekton_tasks_git.yml, policy/lib/refs.rego, policy/lib/refs_test.rego, policy/lib/tekton/trusted.rego, policy/lib/tekton/trusted_test.rego, policy/release/trusted_task.rego, policy/release/trusted_task_test.rego
This new package allows verifying that a certain Task is trusted. It supports both the bundles and the git resolvers.
Eventually, this will supersede the attestation_task_bundle package.
Ref: EC-186
=> Add trusted_task package

policy/release/labels.rego, policy/release/labels_test.rego
Add a new rule to warn users about, currently, optional labels that must not be inherited from the parent image.
Ref: EC-144
=> Add labels.optional_disallowed_inherited_labels

antora/docs/modules/ROOT/pages/trusting_bundles.adoc
This commit adds documentation detailing the process for how to add a new task to the list of Red Hat acceptable tasks.
Resolves: EC-260
=> Add doc for adding to Red Hat trusted task list

policy/task/step_image_registries.rego, policy/task/step_image_registries_test.rego
This allows granular filtering in a policy. For example, it is possible to ignore a failure for the violation affecting a particular Task.
=> Add support for terms in step_image_registries

policy/lib/assertions.rego, policy/lib/assertions_test.rego, policy/release/rpm_ostree_task.rego, policy/release/rpm_ostree_task_test.rego
Add a new policy package, rpm_ostree_task under the release namespace. It is used to verify the rpm-ostree Tekton Task is executed with the expected parameters. All rules are added to the 'redhat' collection.
=> Add rpm_ostree_task package

README.md, antora/docs/modules/ROOT/pages/index.adoc, antora/docs/modules/ROOT/pages/trusting_bundles.adoc, antora/docs/modules/ROOT/templates/acceptable_bundles.hbs, antora/docs/modules/ROOT/templates/release_policy.hbs, policy/pipeline/required_tasks.rego, policy/release/java.rego
The CI system we used to call RHTAP is now called Konflux. Update the docs accordingly.
Ref: [EC-378](https://issues.redhat.com/browse/EC-378)
=> Rename RHTAP to Konflux in docs

policy/release/slsa_source_correlated.rego, policy/release/slsa_source_correlated_test.rego
This adds an additional case in the `_ref` function to handle the SCM URLs, e.g. `https://github.com/org/repository/`. This is needed as the attestation will contain something like
`git+https://github.com/org/repository.git`
=> Tolerate git URL with a slash at the end

Makefile
Was down a rabbit hole debugging [this](https://gitlab.cee.redhat.com/releng/rhtap-release-data/-/merge_requests/198), see also [this](https://github.com/securesign/rekor/pull/239).
Fixes `make check-release` which was failing due to the custom rego functions, and updates `make fetch-att` to produce an accurate `input/input.json` file.
=> Two Makefile fixes

policy/lib/sbom.rego, policy/lib/sbom_test.rego
This is using `ec.oci.blob` function to fetch the SBOM from an OCI blob, expecting a JSON string to be present, which will be unmarshaled and stored in the `data.lib.sbom.cyclonedx_sboms` array.
This all will happen only if the `beta` source directory is included in the policy sources.
Reference: EC-499
=> Fetch SBOM from OCI blob

policy/release/lib/attestations.rego, policy/release/test.rego, policy/release/test_test.rego
For tests emitting IMAGES_PROCESSED result, verify the input image digest has been processed.
Resolves: CVP-4067
=> Add policy check to verify if the digest was scanned

policy/release/lib/attestations.rego, policy/release/test.rego, policy/release/test_test.rego
This reverts commit 901d9e1eab0dbdd3d8842870dfd4ba1b18cea76a. 
Revert this temporarily until ec-cli PR #1486 has been merged.
=> Revert "Add policy check to verify if the digest was scanned"

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/sbom_cyclonedx.rego, policy/release/sbom_cyclonedx_test.rego
We cannot demand that there are components within the SBOM, an example of a valid SBOM without components is an operator bundle which does not contain any executables within it, only descriptors, and it is usually built from `scratch` image.
=> Remove sbom_cyclonedx.contains_components rule

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/source_image.rego
This has caught some folk by surprise, let's bump the effective on by ~1 month and figure out how to exclude folk that do not need to build the source image within that time.
=> Bump enforcing source image existence by a month

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/lib/rule_data.rego, policy/release/schedule.rego, policy/release/schedule_test.rego
Make it so the "no Friday deploys" rule (for example) is used only for EC checks in release pipelines, and not for EC checks in regular pre-merge or post-merge CI pipelines.
Whether we're in a release pipeline is determined by checking the value of the new `pipeline_intention` rule data key.
See also:
* https://github.com/enterprise-contract/ec-cli/pull/1604
* https://github.com/konflux-ci/release-service-catalog/pull/409
Notes:
* Set a null default for the pipeline_intention rule data value since the standard default of an empty list seems less useful.
* This should allow the revert here to be unreverted: https://github.com/release-engineering/rhtap-ec-policy/pull/12
Ref: https://issues.redhat.com/browse/EC-293
=> Ensure schedule checks apply only to releases

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/quay_expiration.rego, policy/release/quay_expiration_test.rego
The quay.expires-after label is used by quay.io to indicate the image doesn't need to be kept indefinitely. The goal is to prevent unintentionally releasing images with that label is set.
There's some dependency on the extra rule data name/value chosen in EC-618 so this is WIP for now.
Ref: https://issues.redhat.com/browse/KFLUXBUGS-1223
=> Prevent release with quay expires-after set

Makefile, policy/release/redhat_manifests.rego, policy/release/redhat_manifests_test.rego
=> Remove requirement for in-image SBOM

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/trusted_task.rego, policy/release/trusted_task_test.rego
When a policy rule emits a violation/warning that contains a `term`, the `term` can be used in an exclude/include clause in a policy config. This is meant to provide fine-grained control over certain policy rules, e.g. ignore a violation but just for a particular Task.
Given how it's used, a `term` should be a piece of information that is not possible to be changed without detection. Otherwise, it becomes trivial to silently apply a certain exclusion to an unintended target.
A Task name is a good candidate for a `term` value. To change the Task name, a change to the Task definition is required. Given our concept of trusted Tasks, this can be easily detected.
A PipelineTask name, on the other hand, is completely within the control of the Pipeline author. Since we do not establish any trust …
=> Use Task name in term for trusted_task.trusted

antora/docs/modules/ROOT/pages/task_policy.adoc, antora/docs/modules/ROOT/partials/task_policy_nav.adoc, policy/lib/k8s.rego, policy/lib/k8s_test.rego, policy/task/step_image_registries.rego, policy/task/trusted_artifacts.rego, policy/task/trusted_artifacts_test.rego
These policy rules are meant to assist Task authors in conforming to the conventions expected by Trusted Artifacts. Mainly, it is important to follow the pattern of using the `_ARTIFACT` suffix for any Trusted Artifact parameter and result.
This PR also includes a small refactoring so we can re-use the helper functions previously defined in the `step_image_registries` package.
NOTE: These are not added to the `redhat` collection because, currently, collections are only supported on the policy rules in the `release` namespace.
Ref: EC-371
=> Add trusted_artifacts task policy package

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/cve.rego, policy/release/cve_test.rego
If the scanning task emits both the new result name (`SCAN_OUTPUT`) and the deprecated one `CLAIR_SCAN_RESULT` the `deprecated_cve_result_name` warning should not be emitted.
Also the second warning about the same issue with the code `deprecated_unpatched_cve_result_name` is removed to reduce the noise.
=> Deprecated CVE result name is ok if new is present

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/lib/tekton/task.rego, policy/lib/tekton/task_results.rego, policy/lib/tekton/task_results_test.rego, policy/lib/tekton/task_test.rego, policy/release/slsa_build_scripted_build.rego, policy/release/slsa_build_scripted_build_test.rego
This change supports all chains artifacts outputs. It uses all outputs to identify the build task.
https://issues.redhat.com/browse/EC-590
=> Support all artifact result outputs

acceptance/features/release.feature, acceptance/samples/policy-input-golden-container.json, example/data/trusted_tekton_tasks.yml, policy/lib/tekton/task_results.rego, policy/lib/tekton/task_results_test.rego
The type-hinting results that Chains expects, e.g. IMAGE_URL, sometimes contain a trailing slash. Chains allows for this behavior by always trimming the spaces around such values. The same should be done by the policy rules.
These changes also use the policy input extracted from the latest golden-container image in the acceptance tests. This now contains a Task that builds the source container image which highlights the bug fixed in this PR.
=> Allow image URLs and digests to contain \n

policy/lib/tekton/task.rego, policy/lib/tekton/task_results.rego, policy/lib/tekton/task_results_test.rego
It is perfectly valid of a Task to emit various results which may conform to different type-hinting formats accepted by Chains.
Prior to this commit, if a Task did this, EC would crash with the generic error:
functions must not produce multiple outputs for same inputs
This commit adds support for such use cases.
=> Allow mixed type-hinting of images

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/trusted_task.rego, policy/release/trusted_task_test.rego
This policy rule is responsible for identifying when a trusted builder Task uses the result from an untrusted Task.
The parameters inspected are scoped to values that look like a digest.This is because, at least with the SLSA Provenance 0.2 format, we cannot easily tell where a paramter came from (Pipeline parameter, default Task Parameter, hard-coded, from another Task, etc). The new policy rule makes an assumption that if a parameter includes a digest, that digest must be accounted for within the Pipeline.
This pull request also includes two other minor commits. One to add supporting helper functions, and the other to tidy up one of the existing test cases.
Fixes #1019
Ref: EC-658
=> Add trusted.trusted_parameters policy rule

antora/docs/modules/ROOT/pages/task_policy.adoc, antora/docs/modules/ROOT/partials/task_policy_nav.adoc, policy/task/trusted_artifacts.rego, policy/task/trusted_artifacts_test.rego
This commit adds a new policy rule, `trusted_artifacts.workspaces`, under the `task` namespace. Its purpose is to disallow general purpose workspaces from being used by Tasks that implement the Trusted Artifacts pattern.
Ref: EC-658
=> Add trusted_artifacts.workspaces rule to task ns

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/lib/attestations.rego, policy/release/lib/attestations_test.rego, policy/release/slsa_source_correlated.rego, policy/release/slsa_source_correlated_test.rego
This PR includes two related changes:
```
Make slsa_source_correlated generic 
This commit modifies the rules in the `slsa_source_correlated` package
so they work with any SLSA Provenance attestation regardless of the
producer. Prior to this change, only attestations generated by Tekton
Chains were taken into account.
```
```
Make source_code_reference_provided a failure 
Prior to this commit, the
`slsa_source_correlated.source_code_reference_provided` policy rule
generated a warning if the expected source code reference was not
provided in the input. When that information is not available, the other
policy rules in the package will pass because there is nothing to match
against. Given that it's easy to ignore errors in different contexts,
this behavior may give users a false sense of …
```
=> Make slsa_source_correlated generic 

policy/lib/tekton/trusted.rego, policy/lib/tekton/trusted_test.rego
If two versions of the Task have the same effective_on one of them will be considered out of date, this is a bit confusing as the latest version could be the one that is deemed out of date.
This changes so that if the proposed out of date task record and the examined task record have the same exact effective_on the task is not considered out of date.
We have this situation now, as the two top records for the buildah task have the same effective on:
```yaml
oci://quay.io/redhat-appstudio-tekton-catalog/task-buildah:0.1:
- effective_on: "2024-06-29T00:00:00Z"
ref: sha256:b8d50716c01160be5deb27dd30f79ae33cc89c72952285cd850323fa0a88b8db
- effective_on: "2024-06-29T00:00:00Z"
expires_on: "2024-06-29T00:00:00Z"
ref: sha256:9f698f0903234093711ab2310891239fdcd6cfda5407f881822e6fa2cb05f771
```
and …
=> Edge case with Tasks that have same effective_on

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/sbom_cyclonedx.rego, policy/release/sbom_cyclonedx_test.rego
Given rule data set to:
```
dissalowed_attributes:
- name: attribute
value: value
- name: another
```
Will disallow any dependency that has properties "attribute" with value value" or "another" (without a value) set.
Reference: https://issues.redhat.com/browse/EC-638
=> Disallow dependencies based on attributes in SBOM

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/lib/rule_data.rego, policy/lib/tekton/trusted.rego, policy/lib/tekton/trusted_test.rego, policy/release/trusted_task.rego
Ernesto (reasonably IMO) assumed that this would work and I can't think of a good reason that it shouldn't, especially since it's such a small change.
It's true that we're moving towards the "trusted artifacts", aka "-oci-ta" tasks which mean we can permit custom tasks without requiring they they are trusted. But still, it's reasonable for teams to want to ensure their custom tasks are trusted, so I like the idea of make it more convenient.
Ref: [EC-709](https://issues.redhat.com/browse/EC-709)
=> Merge rule_data.trusted_tasks into trusted_tasks

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/sbom_cyclonedx.rego, policy/release/sbom_cyclonedx_test.rego
The purpose of this is to ban packages that have an externalReference in their cyclonedx sbom that match some regex in the policy rule data.
This is meant to be useful in particular in conjunction with the [oci-copy](https://github.com/konflux-ci/build-definitions/tree/main/task/oci-copy) task. That task permits copying arbitrary binary content for the purposes of distributing it via an OCI registry. It is not safe in general. Policies should generally forbid it, and not treat it as a trusted task.
In scenarios where it is deemed permissible, the task should be trusted, but only if this rule is also in place which will put limits on what artifacts can be redistributed.
Ref: https://issues.redhat.com/browse/EC-676
=> Add disallowed package external references rule

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/sbom_cyclonedx.rego, policy/release/sbom_cyclonedx_test.rego
I decided that I needed this feature once I learned that `re2` doesn't support negative lookarounds. I intended to use the "disallowed" external packages feature with a negative regex that forbade any external reference that didn't match a small number of permitted urls. That's just not possible with golang regular expressions.
With this, I add a new rule that by default permits every package, but when rule data is provided, it will deny every artifact with packages in its sbom that do not appear explicitly in its allow list of external references.
=> feat: add an explicit allowlist rule for sbom external references

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/olm.rego, policy/release/olm_test.rego
This commit verifies the validity of the pull specs in the operator bundle CSV by checking if they are planned to be released as a part of the input snapshot or are already accessible on the registries they reference.
resolves: CVP-4148
=> Verify all operator CSV pull specs will be valid on release

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/olm.rego, policy/release/olm_test.rego
Instead of trying to resolve the input components, expect pinned references.
=> Expect pinned references in input snapshot for operators

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/lib/tekton/task_test.rego, policy/release/buildah_build_task.rego, policy/release/buildah_build_task_test.rego
The policy no longer requires that the buildah Task is named "buildah", but rather looks at the Tasks that build images and selects those that have the `DOCKERFILE` parameter instead. With that the rule `buildah_task_has_dockerfile_param` doesn't make much sense any more and it has been removed.
Resolves: #1027
=> Redefine DOCKERFILE parameter check

Makefile
Allow running `make watch` or `make watch TEST=data.policy.release` to run the tests and re-run them on changes to files.
=> `watch` target to run tests in watch mode

policy/release/test.rego, policy/release/test_test.rego
The status held in the `result` field of the test output is what was solely considered, so when a test resulted in ERROR (`"result": "ERROR"`) but in addition to that also had failures, e.g. `"result": "ERROR", "failures": 3` the failures were not reported.
This changes the logic so that the individual finding counts are reported as well as the outcome held in `result` field.
Reference: https://issues.redhat.com/browse/EC-620
=> Consider finding counts in addition to status

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/cve.rego
The policy rule `cve.deprecated_cve_result_name` has been removed from any collection since the new result name has not yet been widely adopted. Without this change, users a faced with a warning they cannot act on. This change is about reducing the noise for users.
Ref: EC-751
=> Remove deprecated_cve_result_name from collections

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/olm.rego, policy/release/olm_test.rego
This commit adds a rule that verifies that images from operator bundle CSVs are hosted on approved registries. 
resolves: CVP-4149
=> Verify operator CSV images are from allowed registries

acceptance/go.mod, antora/docs/modules/ROOT/pages/release_policy.adoc, docs/go.mod, policy/release/sbom_cyclonedx.rego, policy/release/sbom_cyclonedx_test.rego
Also, use the same go version in all modules. Failure to do so causes issues when generating docs.
=> Add effective_on support to disallowed_attributes

README.md, policy/lib/result_helper.rego, policy/lib/result_helper_test.rego
Disregarding the readme fix, the first commit is a small change to fix the reported bug, while the second commit is a more holistic refactor, imaging the existence of custom rego with any arbitrary package naming conventions.
Ref: https://issues.redhat.com/browse/EC-831
=> Rework package path logic in result helper

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/slsa_source_version_controlled.rego
The materials section includes other entries besides sha1 digests. The description leads you to believe the policy rule includes those.
https://issues.redhat.com/browse/EC-828
=> Update description to only include sha1 entries

policy/release/rpm_repos.rego, policy/release/rpm_repos_test.rego
Explain in comments that we do intend to match both rpms and modules. Also add some test coverage to confirm and illustrate it.
Ref: https://issues.redhat.com/browse/EC-848
=> Mention module purls in rpm repo id check

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/cve.rego
I also see few occurences of CLAIR_SCAN_RESULT in policy-input-golden-container.json, but I am unsure whether it can be changed right away.
That's why I haven't made the changes there.
Can I also update that file?
=> feat(STONEINTG-660): rename CLAIR_SCAN_RESULT>SCAN_OUTPUT

acceptance/acceptance_test.go, acceptance/features/release.feature, antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/rpm_repos.rego, policy/release/rpm_repos_test.rego
The term is the whole purl found to be in violation. In addition the main difference is that the rule doesn't emit +1 violation when the list is truncated, a notice is added to the message about remaining similar violations instead.
Reference: EC-877
Also, adds `rpm_repos.rule_data_provided` to the `policy_data` collection.
=> Add terms to rpm_repos.ids_known

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/pages/tasks.adoc, policy/release/tasks.rego, policy/release/tasks_test.rego
Note: this came from an internal Slack conversation about how to distinguish between "task is deprecated because we only maintain the newer version" and "task is discontinued". Somewhat related to https://github.com/konflux-ci/build-definitions/pull/1471#discussion_r1776637740
Along with the expires-on annotation, Task authors can optionally define the expiry-message annotation to override the default expiry message. The default is still "Upgrade to a newer version of the Task."
This required moving the 'solution' part of the rule into the 'failure_msg' instead, because 'solution' does not support templating.
=> Make the task expiry message customizable

antora/docs/antora.yml
See https://docs.antora.org/antora/latest/component-with-no-version/
We don't actually have a master branch, so it should have been main to begin with. Likely a copy/paste snafu made in
93b0e925ed36e7f8fa64249c007d7f08c95910bc.
But actually, because we don't build docs for different branches, switching to unversioned should be is better, and by chance it preserves the url path for the policies. I guess since "master" exist the antora build was skipping the url prefix entirely.
(And now we know why ec-policies is the only component without the 'main/' in its url path.)
Drive-by fix while working on...
Ref: https://issues.redhat.com/browse/EC-903
=> Switch to "unversioned" in antora.yml

antora/docs/modules/ROOT/pages/index.adoc, antora/docs/modules/ROOT/pages/policy_bundles.adoc
Trying to avoid this error when building the main website antora docs:
target of xref not found: main@ec-cli::index.adoc
See https://docs.antora.org/antora/latest/component-with-no-version/#reference-an-unversioned-resource
Ref: https://issues.redhat.com/browse/EC-86
=> Specify "unversion" link in ec-cli component

antora/docs/modules/ROOT/pages/index.adoc, antora/docs/modules/ROOT/pages/policy_bundles.adoc
I think this is better since there should be no need to specify a version at all.
Ref: https://issues.redhat.com/browse/EC-86
=> Fixup for last PR: Actually remove the version

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/base_image_registries.rego, policy/release/base_image_registries_test.rego, policy/release/lib/attestations.rego
sbom4life
Fixes: #1155
Ref: EC-892
=> Drop support for BASE_IMAGES_DIGESTS results

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/rpm_repos.rego
Because this check will fail for a image that was not built with the latest version of cachi2, the effective on date was set 30 days out. Hopefully most people would have their Konflux tekton task bundle refs updated by then.
See also:
* https://github.com/containerbuildsystem/cachi2/releases/tag/0.11.0
* https://github.com/konflux-ci/build-definitions/commit/ef11db2b8f47b8bd1c2f7c0ab93fca93ef12b41d
Ref: [EC-876](https://issues.redhat.com/browse/EC-876)
=> Enable rpm repo id check in redhat collection effective in 30 days

.github/workflows/pre-merge-ci.yaml, Makefile
Uses `unshare` to run the Rego tests on Linux without network access. This makes sure that the tests are not depending on outside service and that all network access is mocked.
=> Run tests offline on Linux

Makefile
In #1188 tests were made to run without network. This works if the local golang module cache already contains the required dependencies, i.e can be built offline. When a dependency is not available from the cache, due to the offline nature of the namespace the build fails.
This circumvents that by invoking the equivalent of `ec opa version` so that the `ec` command is build outside the offlined namespace.
=> Make sure `ec` is built with network

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/lib/rule_data.rego, policy/release/cve/cve.rego, policy/release/cve/cve_test.rego
If present the Clair report attached to the image will be used and consulted instead of the aggregate present in `SCAN_OUTPUT` Task result.
This allows us to filter out the vulnerabilities that are made public within X number of leeway days.
Reference: https://issues.redhat.com/browse/EC-838
=> Use of clair report from OCI and CVE leeway

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/cve/cve.rego
Documents the existing `*_security_levels` and the newly added `cve_leeway` rule data configuration.
Seems that the double newline is needed to emit a single newline in certain parts of the annotation description.
Reference: https://issues.redhat.com/browse/EC-840
=> Add documentation for CVE rule data

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/lib/konflux/konflux.rego, policy/lib/konflux/konflux_test.rego, policy/release/base_image_registries/base_image_registries.rego, policy/release/base_image_registries/base_image_registries_test.rego, policy/release/sbom/sbom.rego, policy/release/sbom/sbom_test.rego
Currently, Konflux does not create an SBOM for Image Indexes: https://issues.redhat.com/browse/KONFLUX-4330
Until then, do not trigger a violation when an SBOM is not found for such images.
Today, it's not possible to determine if the image being validated is an Image Index or an Image Manifest, see
https://github.com/enterprise-contract/ec-cli/issues/2121. The Image Index detection is done via Konflux-specific heuristics as a workaround.
=> Ignore missing SBOM for Image Indexes

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/lib/sbom/sbom.rego, policy/release/sbom/sbom_test.rego, policy/release/sbom_cyclonedx/sbom_cyclonedx.rego, policy/release/sbom_cyclonedx/sbom_cyclonedx_test.rego
This adds a new `allowed_package_sources` policy that can gate content fetched by cachi2. This rule take a lot from the `allowed_external_references`, but makes it specific to content fetched by cachi2, because it is not uncommon for dependencies fetched by other means to define externalReferences of type `distribution`. Cachi2 currently produces the mentioned external reference only for packages fetched with the generic fetcher ([docs WIP](https://github.com/containerbuildsystem/cachi2/pull/718)) that always produces a `pkg:generic` purl, but it is possible it will be extended to other package managers supported by cachi2 as well. 
The rule data for this policy are structured as a list of regex patterns for a given purl type. Examples in tests.
Finally, this is my first contribution to …
=> Add allowed package sources policy

policy/lib/json/schema.rego, policy/lib/json/schema_test.rego, policy/lib/tekton/trusted.rego, policy/lib/tekton/trusted_test.rego
This commit demotes duplicated entries in the trusted tasks from a violation to warning. The current understanding is that preventing duplicated items is nice to have but does not affect functionality. As such, these should not trigger an EC violation.
=> Set dupe entries as warnings in trusted tasks

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/buildah_build_task/buildah_build_task.rego, policy/release/buildah_build_task/buildah_build_task_test.rego
The `PRIVILEGED_NESTED` parameter must not be set to `true`.
Reference: https://issues.redhat.com/browse/EC-1011
=> Add rule for PRIVILEGED_NESTED buildah parameter

antora/docs/modules/ROOT/pages/task_policy.adoc, antora/docs/modules/ROOT/partials/task_policy_nav.adoc, policy/task/step_image_registries/step_image_registries.rego, policy/task/step_images/step_images.rego, policy/task/step_images/step_images_test.rego
Resolves: https://issues.redhat.com/browse/EC-912
=> Check accessibility of Step images

policy/lib/tekton/trusted.rego, policy/lib/tekton/trusted_test.rego
Turns out we like having duplicate entries, see HACBS-2394[1]
Reference: https://issues.redhat.com/browse/EC-1015
[1] https://issues.redhat.com/browse/HACBS-2394
=> Remove the unique items constraint

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/base_image_registries/base_image_registries.rego, policy/release/base_image_registries/base_image_registries_test.rego
This commit changes the policy rule
`base_image_registries.base_image_permitted` so it includes a term in its result. The term is the repository portion of the base image reference - everything but the tag and digest.
This allows users to allow certain base image registries as an exception, especially if time bound, e.g.:
```yaml
volatileConfig:
exclude:
- value: 'base_image_registries.base_image_permitted:my-shady-registry.io/foo/bar'
effectiveUntil: '2024-12-01T00:00:00Z'
```
Ref: EC-649
=> Emit term for base_image_permitted

policy/lib/json/schema.rego, policy/lib/json/schema_test.rego, policy/lib/tekton/trusted.rego
We're no longer requiring unique items so this makes the call to
`with_severity_for_pattern` dead code.
Reference: https://issues.redhat.com/browse/EC-1015
=> Remove severity reduction to warning

antora/docs/modules/ROOT/pages/task_policy.adoc, policy/task/step_images/step_images.rego, policy/task/step_images/step_images_test.rego
Although the implementation of ec.oci.image_manifest does return nil if the Image Manifest is not found, rego converts that to no value at all. Thus, asserting that the returned value is nil will never be true causing this policy rule to always pass.
This commit changes the rule evaluation to check for the lack of a value instead.
=> Fix step_images.step_images_accessible check

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/collection/rhtap_jenkins/rhtap_jenkins.rego, policy/release/collection/rhtap_multi_ci/rhtap_multi_ci.rego
A fixup for #1236 which introduced the rhtap-multi-ci collection and deprecated the rhtap-{jenkins,gitlab,github} collections, (two of which hadn't been included in the docs yet anyhow).
Ref: https://issues.redhat.com/browse/EC-1032
=> Show rhtap-multi-ci collection in generated docs

policy/release/cve/cve_test.rego
This commit modifies how the CVE report used in cve_test.rego is generated. Hopefully, this makes it easier to understand the process and make modifications later on.
=> Make cve test data readable

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/collection/redhat_rpms/redhat_rpms.rego, policy/release/rpm_pipeline/rpm_pipeline.rego, policy/release/rpm_pipeline/rpm_pipeline_test.rego
Ensure that all tasks building the RPM come from an approved pipeline.
=> Add a check for the RPM build pipleline

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/olm/olm.rego, policy/release/quay_expiration/quay_expiration.rego, policy/release/schedule/schedule.rego
The goal here is to make the schedule rules only apply to production releases.
The konflux-ci release pipelines don't yet provide these new pipeline_intention values. I'll follow up in a separate PR with them to provide those.
=> Handle more pipeline_intention values

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/base_image_registries/base_image_registries.rego
Previously, the check asserted that there was at least 1 CycloneDX SBOM. Use the 'sbom.all_sboms' property instead to also count SPDX SBOMs.
Also reword the description of the check. Make it less specific to avoid having to explain where the base images are in each SBOM format. All the check does is assert that there are some SBOMs, anyway.
=> Fix SBOM count condition for base_image_info_found

.github/workflows/docs.yaml
For a brief period both website repos existed, but now the old one is gone. This should fix CI breakage when triggering a website update.
Ref: https://issues.redhat.com/browse/EC-1081
=> Remove old docs update trigger

hack/update-infra-deployments.sh
The release-policy bundle has been given a floating tag of "konflux".
=> Remove updates to the release-policy bundle

README.md, antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/olm/olm.rego, policy/release/olm/olm_test.rego
We were previously only able to verify certain pullspecs at build-time
which resulted in a failed test. This would prevent multiple images from
being built and all staged for release. Even if the image references are
valid at release time, the check used was old and the results are not
updated without a rebuild.
If a task has a result named RELATED_IMAGES_DIGEST, all references in the
json array contained within the pushed file will be checked for validity.
implements: EC-965
=> feat(ec-965): verify a set of pullspecs related to an image

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/slsa_source_correlated/slsa_source_correlated.rego, policy/release/slsa_source_correlated/slsa_source_correlated_test.rego
Instead of using `sha1` as a digest algorithm, the in-toto spec allows using `gitCommit` to give additional meaning to the digest: https://github.com/in-toto/attestation/blob/main/spec/v1/digest_set.md#gitcommit-gittree-gitblob-gittag
The spec docs are a somewhat confusing on this which lead it to be interpreted as:
```
gitCommit="$(printf 'commit 3\0'`git rev-parse HEAD` | sha1sum)"
```
However, the intended use of `gitCommit` is to capture a git commit ID as is:
```
gitCommit="$(git rev-parse HEAD)"
```
Fixes #1037
=> Use gitCommit as intended

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/lib/sbom/rpm.rego, policy/lib/sbom/rpm_test.rego, policy/release/rpm_repos/rpm_repos.rego, policy/release/rpm_repos/rpm_repos_test.rego
This change moves `all_rpm_entities` and `rpms_from_sbom` to a lib module so it can be used by other policy packages. This is in preparation for EC-1142.
=> Move SBOM rpm processing to lib

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/lib/rule_data.rego, policy/release/rpm_packages/rpm_packages.rego, policy/release/rpm_packages/rpm_packages_test.rego
This new policy package includes a policy rule that is used to ensure the installed RPMs are of the same version across the different Image Manifests of an Image Index.
Ref: EC-1142
=> Add `rpm_packages` policy package

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/olm/olm.rego, policy/release/olm/olm_test.rego
We missed testing the related images against the
allowed_registry_prefixes in a previous change. We now add an additional policy check to ensure that related images detected are from approved registries.
=> fix: enforce related images are from allowed registries

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/olm/olm.rego, policy/release/olm/olm_test.rego
If OLM bundle images are multi-arch then the image pulled by the client will be interpolated to match the client's platform. This can result in inconsitent behaviors between architectures. Instead, a single image manifest should be created since there is no binary and therefore no architecture dependencies.
resolves: KONFLUX-6986
=> feat(KONFLUX-6986): OLM bundle images should not be multi-arch

policy/lib/image/image.rego, policy/lib/image/image_test.rego, policy/release/olm/olm_test.rego
image.parse was allowing invalid hostnames.
Adding a regex to strengthen the validation.
https://issues.redhat.com/browse/EC-1153
=> Make image.parse only validates valid hostnames

docs/go.mod
Security updates are requiring `>1.23` for the go version.
=> Update go for module updates

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/attestation_type/attestation_type.rego, policy/release/cve/cve.rego, policy/release/provenance_materials/provenance_materials.rego, policy/release/rpm_repos/rpm_repos.rego, policy/release/rpm_signature/rpm_signature.rego, policy/release/sbom/sbom.rego, policy/release/sbom_cyclonedx/sbom_cyclonedx.rego, policy/release/sbom_spdx/sbom_spdx.rego, policy/release/schedule/schedule.rego, policy/release/slsa_build_build_service/slsa_build_build_service.rego, policy/release/slsa_build_scripted_build/slsa_build_scripted_build.rego, policy/release/slsa_provenance_available/slsa_provenance_available.rego, policy/release/slsa_source_correlated/slsa_source_correlated.rego, policy/release/slsa_source_version_controlled/slsa_source_version_controlled.rego, policy/release/tasks/tasks.rego, policy/release/test/test.rego, policy/release/trusted_task/trusted_task.rego
This adds all the tests I could get passing against the latest rpm builds. Note that it's possible that some of these are passing just because the data isn't there; therefore I didn't add anything obviously 'container' related. Not sure how the CVE definitions will end up working.
=> Add passing tests to redhat_rpms collection

go.mod, go.sum
ec-cli upgrades are blocked unless the versions is >= what ec-cli has.
```
go: module github.com/enterprise-contract/ec-cli@v0.7.36 requires go >= 1.23.6; switching to go1.23.8
```
=> go must match version with ec-cli

policy/lib/sbom/rpm.rego, policy/lib/sbom/rpm_test.rego, policy/release/rpm_repos/rpm_repos_test.rego
The name is changing and so the annotations we need to look for in sbom component/package lists are changing accordingly. Match both the old and new names so we can transition smoothly.
There are two different matches, one for CycloneDX and one for SPDX formatted SBOMs.
Ref: https://issues.redhat.com/browse/EC-1176
=> Support both old and new names for cachi2/hermeto

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/lib/tekton/refs.rego, policy/lib/tekton/refs_test.rego, policy/lib/tekton/trusted.rego, policy/lib/tekton/trusted_test.rego, policy/release/trusted_task/trusted_task.rego, policy/release/trusted_task/trusted_task_test.rego
Extend the trusted tasks lookup logic to also support bundle references without tag information, as long as a match for the digest is found. Now the presence of an untagged task reference throws a warning instead of a violation.
Ref: https://issues.redhat.com/browse/EC-712
=> Emit warning for bundle references without tags

.gitignore, Makefile, hack/ec-opa.sh, hack/regal.sh
The OPA VSCode plugin relies on the OPA and Regal binaries to be available on the system. The exact version of those matter. In fact, the OPA binary used has to be the one wrapped by the EC CLI, i.e. `ec opa`. To make this easier, we track those dependencies in go.mod and use bash scripts to call `go run ...` on the corresponding modules. This works ok, but it's kind of slow, and it's likely the reason the VSCode plugin crashes all the time.
This commit changes the bash script to no longer use `go run`. Instead, it introduces Make targets to create the required binaries. The bash scripts are modified to automatically call the Make targets, which should be a no-op if the binaries don't need to be created, and then invoking the binary directly.
This should give us a snappier development …
=> Use binaries for OPA IDE integration

policy/release/collection/rhtap_multi_ci/rhtap_multi_ci.rego, policy/release/rpm_packages/rpm_packages.rego, policy/release/rpm_packages/rpm_packages_test.rego
The files being fixed here were using the old convention of nested namespace package names, which we used to do, but stopped doing in https://github.com/enterprise-contract/ec-policies/pull/1198 .
The symptom is a little unexpected -- some missing description/solution text in a violation report due to how the the metadata lookup is done by the cli. This could actually could be a separate bug, out of scope in this PR, but possibly in scope for https://issues.redhat.com/browse/EC-945 which I am also looking at currently.
Anyway, this change should be enough to fix EC-1233.
Note: The collection.rhtap_multi_ci change might not have any impact, but I'll change it anyhow so it's consistent with the others.
Ref: https://issues.redhat.com/browse/EC-1233
=> Shorten some long unflat package names

acceptance/samples/README.md, antora/docs/modules/ROOT/pages/authoring.adoc, antora/docs/modules/ROOT/pages/trusting_tasks.adoc
References to ec-cli docs from ec-policies docs are broken, as they contain a reference to branch name "main".
Remove the branch from the URL to fix the links.
Ref: EC-1230
=> Docs: fix broken links to ec-cli docs in ec-policies docs

antora/docs/modules/ROOT/pages/release_policy.adoc, policy/release/olm/olm.rego
OLM Bundle images should be built for a single image architecture. They should not be an OCI image index.
(Redoing the original PR from #1383).
=> Correct Guildance for OLM Bundle Image Index Check

acceptance/go.mod, acceptance/go.sum, go.mod, go.sum
Done like this (in two locations: `.`, and `./acceptance`):
go mod edit -replace \
muzzammil.xyz/jsonc=github.com/muhammadmuzzammil1998/jsonc@v1.0.0
go mod tidy
No Jira, but here's [a slack thread](https://redhat-internal.slack.com/archives/C031J4KBFME/p1748442512109569).
=> Mod edit for jsonc dependency

antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/release/git_branch/git_branch.rego
When we generate the docs, we look for package metadata to use in the documentation for the package.
This should fix the "Error: Package path 'data.git_branch' not found for rule 'policy/release/git_branch/git_branch.rego:6" message in the brand new docs generation in PR #1408.
See also PR #1360 where this package was added recently.
Tangentially related to...
Ref: https://issues.redhat.com/browse/EC-984
=> Add missing metadata for new git_branch package

policy/release/trusted_task/trusted_task.rego, policy/release/trusted_task/trusted_task_test.rego
Make sure the new `run-script-oci-ta` task can pass an image ref and digest via the ADDITIONAL_BASE_IMAGES param to the build task without producing a violation.
See commit messages for more details. Includes some additional test coverage for the _trusted_build_digest rules.
Assisted-by: Claude 3.7 Sonnet (with Cursor)
Ref: https://issues.redhat.com/browse/EC-1303
=> Allow pre build script runner image digest

antora/docs/modules/ROOT/pages/packages/release_pre_build_script_task.adoc, antora/docs/modules/ROOT/pages/release_policy.adoc, antora/docs/modules/ROOT/partials/release_policy_nav.adoc, policy/lib/tekton/task.rego, policy/lib/tekton/task_test.rego, policy/release/pre_build_script_task/pre_build_script_task.rego, policy/release/pre_build_script_task/pre_build_script_task_test.rego, policy/release/trusted_task/trusted_task.rego
Create a new rule that verifies that the parameter SCRIPT_RUNNER_IMAGE
contains an image reference coming only from allowed repositories.
It uses the 'allowed_registry_prefixes' rule_data as list of
allowed registries, that is also used in the base image checks.
Ref: https://issues.redhat.com/browse/EC-1241
=> Enforce only allowed images for pre-build script

antora/docs/modules/ROOT/pages/trusting_tasks.adoc
This commit updates references to the config repository from `enterprise-contract/config` to `conforma/config`
Ref: EC-1115
=> chore: update references to config repo

policy/release/pre_build_script_task/pre_build_script_task.rego, policy/release/pre_build_script_task/pre_build_script_task_test.rego
This commit reduces the scope of the rule
'pre_build_script_task_runner_image_in_sbom' by filtering out image indexes from the check.
This is because if we ensure that all the references in an image index are in the SBOM, we don't need to check the image index itself.
=> Exclude image index from 'pre build image in SBOM'

antora/docs/modules/ROOT/pages/packages/release_rpm_packages.adoc, policy/release/rpm_packages/rpm_packages.rego
Since this causes bogus violations for some teams, and there's no solid workaround, let's disable it again while we work on a solution, (rather than force all impacted teams to create custom excludes in the ECP policy.yaml).
See the Jira for a longer explanation.
I chose the date to give enough time to resolve EC-1354.
Ref: https://issues.redhat.com/browse/EC-1354
=> Disable the rpm uniqueness check once again

antora/docs/modules/ROOT/pages/packages/release_hermetic_task.adoc, policy/release/hermetic_task/hermetic_task.rego
* Conforma log rendered the error:
```
["attestation_type.known_attestation_type"],"description": "Verify the task in the PipelineRun attestation was invoked with the proper parameters to make the task execution hermetic. To exclude this rule add \"hermetic_task.hermetic\" to the `exclude` section of the policy configuration.",awk: cmd. line:1: (FILENAME=- FNR=64634) fatal: not enough arguments to satisfy format string
`"solution": "Make sure the task '%s' has the input parameter 'HERMETIC' set to 'true'.",'
^ ran out for this one 
```
* I **_suspect_** that its because the solution fields of Rego rules are not substituted with the values from the "lib.result_helper" function. This substituion works only with the "failure_msg field.
* So, I removed the `%s` field from the solution field. …
=> Remove unsubstituted format string `%s` from solution field of hermetic_task.hermetic rule

policy/release/trusted_task/trusted_task.rego, policy/release/trusted_task/trusted_task_test.rego
The violation description for the rule 'trusted_task.trusted' informs the user when the violation can be resolved by updating the task digest to a newer version.
Anyway, this helper description was only implemented for PipelineRuns that use Trusted Artifacts.
This commit extends it also to PipelineRuns that don't use Trusted Artifacts.
Ref: https://github.com/conforma/policy/pull/1394
Ref: https://issues.redhat.com/browse/EC-1269
=> Extend 'outdated task' message to non-ta pipelines

.github/workflows/release.yaml
- Attempt to make the direction to include a link to Jira clearer
- Include all changes with Jira link
- Make the release summary oriented to changes in policy and rules
=> Tweak gemini prompt for release notes

policy/lib/tekton/trusted.rego
It should not happen, but just in case there are duplicate entries, let's handle it without throwing errors.
Note: I considered sorting by the expiration date and pick the earliest date, but decided that would make it seem like we intend to support the duplicate records, which is not the case. Let's keep this workaround is as minimal as possible.
This is the duplicate record we're seeing right now in the acceptable bundles data:
oci://quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.2:
...
- expires_on: "2025-10-11T00:00:00Z"
ref: sha256:b424894fc8e806c12658daa565b835fd2d66e7f7608afc47529eb7b410f030d7
...
- expires_on: "2025-09-13T00:00:00Z"
ref: sha256:b424894fc8e806c12658daa565b835fd2d66e7f7608afc47529eb7b410f030d7
(How it got there is not clear, but we should figure it …
=> Workaround dupe entries in trusted task list

antora/docs/modules/ROOT/pages/packages/release_rpm_packages.adoc, policy/lib/string_utils.rego, policy/lib/string_utils_test.rego, policy/release/rpm_packages/rpm_packages.rego, policy/release/rpm_packages/rpm_packages_test.rego
Avoid unwanted violations when there are more than one version of the same rpm in an images SBOM.
See longer explanations in the commit messages.
Ref: https://issues.redhat.com/browse/EC-1354
=> Improve the mismatched rpm versions across multi-arch images check

policy/lib/image/image.rego, policy/lib/image/image_test.rego
The old regex only supported a hostname that always contained a "." character. This however exclude valid hostnames like "localhost".
This change updates a regex to support hostname, optional port and path.
This issue was discovered while integrating Conforma checks into SBOM generator test suite to make sure generators are inline with Conforma rules.
JIRA: ISV-6206
=> fix: Extend a OCI reference regex to support generic hostname
