conforma/policy

- .github/workflows/pre-merge-ci.yaml
- Makefile
- README.md
As suggested by @lcarva in #1.
> Check the sha when installing opa

- policies/lib/config.rego
This should help make the M4 demo from HACBS-357 go more smoothly.
Also I sorted the list.
> Add one more registry to allowed list

- Makefile
- README.md
- policies/test.rego
Stolen from @lcarva 's suggestion on slack just now.
> Add make helper to run entr for live TDD

- policies/examples/time_base_test.rego
- policies/examples/time_based.rego
- policies/main.rego
- policies/main_test.rego
https://issues.redhat.com/browse/HACBS-308
I consider this PR complete but I'm marking it as a draft because a discussion is needed to determine if this is the right direction we want to take.
> Add support for future policies

- .gitignore
- Makefile
- policies/attestation_type.rego
- policies/attestation_type_test.rego
- policies/step_image_registries.rego
- policies/step_image_registries_test.rego
See also https://github.com/redhat-appstudio/build-definitions/pull/105 which should be merged at the same time.
> Conftest compatibility tweaks

- .github/workflows/pre-merge-ci.yaml
- Makefile
- README.md
- docs.tmpl
- docs/_config.yml
- docs/index.md
- policies/attestation_type.rego
- policies/not_useful.rego
- policies/step_image_registries.rego
- policies/test.rego
> Generate policy docs from rego annotations

- Makefile
- docs/index.md
- policies/attestation_type.rego
- policies/attestation_type_test.rego
- policies/lib/attestations.rego
- policies/lib/attestations_test.rego
- policies/step_image_registries.rego
- policies/step_image_registries_test.rego
> Support pipelinerun attestations

- Makefile
- README.md
> Add a Makefile script to install conftest

- policy/release/lib/attestations.rego
- policy/release/lib/attestations_test.rego
Creating task helper methods.
* check for existence of a task
* task result check
* task succcess
> task helper methods

- POLICY_AUTHORING.md
https://issues.redhat.com/browse/HACBS-459
> Add docs to explain annotations usage to authors

- Makefile
- README.md
- antora-docs/antora.yml
- antora-docs/modules/ROOT/nav.adoc
- antora-docs/modules/ROOT/pages/index.adoc
- docs/index.md
- docsrc/index.adoc.tmpl
- docsrc/index.md.tmpl
- docsrc/static.yaml
The signficant change is in the first commit. The other three commits are related tweaks and improvements.
> Support doc inclusion in the HACBS antora docs build

- policy/lib/main_denies.rego
- policy/lib/main_denies_test.rego
- policy/lib/time.rego
- policy/lib/time_test.rego
> Move effective_current_time_ns to lib/time

- policy/lib/image.rego
- policy/lib/image_test.rego
> Add parser for image references

- antora-docs/modules/ROOT/pages/index.adoc
- policy/lib/time.rego
- policy/lib/time_test.rego
- policy/release/attestation_task_bundle.rego
- policy/release/attestation_task_bundle_test.rego
https://issues.redhat.com/browse/HACBS-748
> Add rule to verify Task bundle ref

- antora-docs/modules/ROOT/pages/index.adoc
- policy/release/attestation_task_bundle.rego
- policy/release/attestation_task_bundle_test.rego
- policy/release/main_test.rego
> Unacceptable task bundle is denied

- antora-docs/modules/ROOT/pages/index.adoc
- policy/release/attestation_task_bundle.rego
- policy/release/attestation_task_bundle_test.rego
> Enable deny rules for task bundle ref checks and fix bundle data lookup

- .github/workflows/docs.yaml
- .gitignore
- Makefile
- antora-playbook.yml
- supplemental-ui/partials/header-content.hbs
Builds the documentation using Antora and publishes the built artifact
to GitHub pages.
> Publish documentation to GitHub Pages

- antora/ec-policies-antora-extension/package.json
Since it's a probably a breaking change let's make it easier to see if we have the right version.
> Version number bump for antora extension

- data/rule_collections.yml
- policy/lib/assertions.rego
- policy/lib/include_exclude_rules.rego
- policy/lib/include_exclude_rules_test.rego
- policy/lib/main_denies.rego
- policy/lib/main_denies_test.rego
- policy/release/main_test.rego
- policy/release/test.rego
- policy/release/test_test.rego
It's messy but the general idea is in place. (Review comments welcome but only if you feel like an early preview.)
> Include exclude plus rule collections

- antora/docs/modules/ROOT/nav.adoc
- antora/docs/modules/ROOT/templates/policy_configuration.hbs
- antora/docs/rule_collections.yml
- antora/ec-policies-antora-extension/index.js
Preview at https://simonbaird.github.io/ec-policies/ec-policies/policy_configuration.html .
> Add some docs for the new rule inclusion config

- policy/release/attestation_task_bundle_test.rego
- policy/release/attestation_type_test.rego
- policy/release/lib/attestations.rego
- policy/release/lib/attestations_test.rego
- policy/release/step_image_registries_test.rego
- policy/release/tasks_test.rego
https://issues.redhat.com/browse/HACBS-1071
> Recognize the new buildType values

- antora/ec-policies-antora-extension/package-lock.json
> npm lockfile updating opa-inspect to latest version

- Makefile
> Update conftest and opa

- policy/pipeline/basic.rego
- policy/pipeline/required_tasks.rego
- policy/pipeline/task_bundle.rego
- policy/release/authorization.rego
- policy/release/java.rego
- policy/release/step_image_registries.rego
- policy/release/tasks.rego
- policy/release/test.rego
* Simplify rules by using helpers
* Prefer "some ... in" for iteration
* Remove unnecessary statements
* Use "contains ... if" style
* Use rule_data helper function
> A few more style updates

- antora/docs/modules/ROOT/templates/acceptable_bundles.hbs
- policy/pipeline/task_bundle.rego
- policy/release/attestation_task_bundle.rego
https://issues.redhat.com/browse/HACBS-1236
> Explain acceptable bundles

- policy/release/slsa_available.rego
- policy/release/slsa_available_test.rego
https://issues.redhat.com/browse/HACBS-1275
> Add initial check for SLSA Available requirement

- policy/pipeline/task_bundle.rego
- policy/release/attestation_task_bundle.rego
> Explain acceptable bundles for remaining rules

- policy/release/base_image_registries.rego
- policy/release/base_image_registries_test.rego
- policy/release/lib/attestations.rego
- policy/release/lib/attestations_test.rego
https://issues.redhat.com/browse/HACBS-1291
> Add policy to restrict base images

- .github/workflows/push-bundles.yaml
> Fix path match in bundles workflow trigger

- antora/docs/modules/ROOT/templates/policy_configuration.hbs
Updated policy_configuration documentation to reflect changes made under HACBS-1330.
Signed-off-by: Rob Nester <rnester@redhat.com>
> Update documentation for collections

- policy/release/slsa_build_scripted_build.rego
- policy/release/slsa_build_scripted_build_test.rego
https://issues.redhat.com/browse/HACBS-1273
> Add SLSA - Build - Scripted Build

- data/rule_collections.yml
This collection represents all the policy rules that must pass in order to achieve SLSA Level 1 compliance.
https://issues.redhat.com/browse/HACBS-1272
> Add SLSA1 collection

- data/rule_collections.yml
- policy/release/slsa_build_scripted_build.rego
- policy/release/slsa_provenance_available.rego
- policy/release/slsa_provenance_available_test.rego
> Improve SLSA docs

- policy/release/slsa_source_version_controlled.rego
- policy/release/slsa_source_version_controlled_test.rego
https://issues.redhat.com/browse/HACBS-1278
> Add SLSA - Source - Version Controlled policy

- data/rule_data.yml
- policy/release/slsa_build_build_service.rego
- policy/release/slsa_build_build_service_test.rego
> Add SLSA - Build - Build Service policy rule

- data/rule_data.yml
- policy/release/step_image_registries.rego
- policy/release/step_image_registries_test.rego
Partially addresses: https://issues.redhat.com/browse/HACBS-1395
> Move step registries data to data/rule_data.yml

- policy/release/slsa_build_scripted_build.rego
- policy/release/slsa_build_scripted_build_test.rego
When comparing the subjects given `IMAGE_URL` and `IMAGE_DIGEST` task results with the attestation subject in cases when `IMAGE_URL` contains the image tag, and the attestation subject.name doesn't we still don't want to report a violation if `IMAGE_DIGEST` matches subject.digest.
Given that we're now removing strings from subject and results to compare without tags, we also want to be careful not to compare empty strings and consider them valid. I think.
> Tolerate missing or different tag in subject

- data/rule_collections.yml
https://issues.redhat.com/browse/HACBS-1281
> Add slsa3 collection

- policy/release/tasks.rego
- policy/release/tasks_test.rego
https://issues.redhat.com/browse/HACBS-1238
> Use time-based required tasks list in release

- policy/pipeline/required_tasks.rego
- policy/pipeline/required_tasks_test.rego
https://issues.redhat.com/browse/HACBS-1238
> Use time-based required tasks list in pipeline

- policy/lib/tekton/task.rego
- policy/lib/tekton/task_test.rego
- policy/pipeline/required_tasks.rego
- policy/pipeline/required_tasks_test.rego
- policy/release/tasks.rego
- policy/release/tasks_test.rego
> Share code for time-based required tasks

- policy/lib/tekton/task.rego
- policy/lib/tekton/task_test.rego
- policy/pipeline/required_tasks.rego
- policy/release/base_image_registries.rego
- policy/release/hermetic_build_task.rego
- policy/release/hermetic_build_task_test.rego
- policy/release/java.rego
- policy/release/lib/attestations.rego
- policy/release/lib/attestations_test.rego
- policy/release/slsa_build_scripted_build.rego
- policy/release/tasks.rego
- policy/release/test.rego
https://issues.redhat.com/browse/HACBS-1465
Also move some relevant helpers to `lib.tkn`.
> Add hermetic build task policy

- Makefile
- policy/release/attestation_type_test.rego
- policy/release/base_image_registries_test.rego
- policy/release/java_test.rego
- policy/release/slsa_build_build_service_test.rego
- policy/release/slsa_provenance_available_test.rego
- policy/release/step_image_registries_test.rego
- policy/release/test_test.rego
> Use default data in tests

- policy/lib/tekton/task.rego
- policy/release/buildah_build_task.rego
- policy/release/buildah_build_task_test.rego
deny remote url for Dockerfile
> deny remote Dockerfile

- antora/docs/modules/ROOT/templates/policy_configuration.hbs
- antora/docs/rule_data.yml
https://issues.redhat.com/browse/HACBS-1455
> Add rule data documentation

- policy/artifacthub-repo.yml
- policy/pipeline/artifacthub-pkg.yml
- policy/release/artifacthub-pkg.yml
This adds the repo file for ownership verification and the pkg files for each package. The packages are split between release and pipeline.
> Creating metadata files for artifact hub

- Makefile
* conftest installation now works on macos
* conftest/opa will be installed if needed by another target
Signed-off-by: arewm <arewm@users.noreply.github.com>
> Simplify Makefile consumption for new contributors

- antora/docs/modules/ROOT/templates/policy_configuration.hbs
- data/rule_data.yml
- policy/lib/rule_data.rego
- policy/lib/rule_data_test.rego
- policy/release/attestation_type.rego
- policy/release/base_image_registries.rego
- policy/release/java.rego
- policy/release/slsa_build_build_service.rego
- policy/release/slsa_build_build_service_test.rego
- policy/release/slsa_provenance_available.rego
- policy/release/step_image_registries.rego
- policy/release/test.rego
[HACBS-1575](https://issues.redhat.com/browse/HACBS-1575) but also includes some other changes, in particular moving some defaults out of the rule_data.yml file.
> Rule data changes

- .github/workflows/push-bundles.yaml
- Makefile
- data/rule_data.yml
- hack/pr-infra-deployments.sh
- hack/update-bundles.sh
- policy/lib/rule_data.rego
Move the bundle pushing to a bash script that detects if a push is needed. Copy the technique used in build-definitions repo, see hack/build-and-push.sh.
> Smarter bundle pushing

- Makefile
We report coverage in two ways by outputting an error if code coverage of 100% is not met to the stdout and by generating the `coverage.json` file. Now this requires executing `opa test` twice.
This removes the `coverage-report` target and introduces the generation of `coverage.json` in the `quiet-test` target, removing the need to run `opa test` twice for the coverage report.
> Execute `opa test` once for coverage report

- hack/pr-infra-deployments.sh
The value of the key needs to be taken from the `CM_KEY` variable.
> Make sure the correct key is set

- Makefile
Also remove some stale commentary.
> Use golden image as default in `make fetch-att`

- data/rule_data.yml
- policy/lib/rule_data.rego
See commit 598a37e for explanation.
> One more bundle uniqueness number bump

- antora/docs/modules/ROOT/pages/policy_bundles.adoc
> Update docs to use --all-namespaces

- antora/ec-policies-antora-extension/index.js
- antora/ec-policies-antora-extension/package-lock.json
- antora/ec-policies-antora-extension/package.json
We don't seem to be using the glob package, so let's remove it and trim down the dependencies.
> Remove the glob package from the Antora extension

- antora/docs/modules/ROOT/pages/index.adoc
Remove duplicate line created as a result of commit for HACBS-1568
Signed-off-by: Rob Nester <rnester@redhat.com>
> REMOVE duplicate line

- .github/workflows/enable-auto-merge.yaml
https://issues.redhat.com/browse/HACBS-1600
> Enable automerge for appstudio-staging-ci PRs

- .github/workflows/enable-auto-merge.yaml
https://issues.redhat.com/browse/HACBS-1600
> Grant write access to the auto-merge workflow

- Makefile
To do the more sophisticated replaces it was necessary to convert the sed commands to yq using a technique copied from hack/pr-infra-deployments.sh in the ec-cli repo.
> Use the current branch in make docs-preview

- policy/lib/tekton/task.rego
- policy/lib/tekton/task_test.rego
- policy/pipeline/required_tasks.rego
- policy/pipeline/required_tasks_test.rego
- policy/release/base_image_registries.rego
- policy/release/base_image_registries_test.rego
- policy/release/buildah_build_task.rego
- policy/release/buildah_build_task_test.rego
- policy/release/hermetic_build_task.rego
- policy/release/hermetic_build_task_test.rego
- policy/release/java.rego
- policy/release/java_test.rego
- policy/release/lib/attestations.rego
- policy/release/lib/attestations_test.rego
- policy/release/slsa_build_scripted_build.rego
- policy/release/slsa_build_scripted_build_test.rego
- policy/release/tasks.rego
- policy/release/tasks_test.rego
- policy/release/test_test.rego
https://issues.redhat.com/browse/HACBS-1690
> Reduce checks on acceptable bundles

- antora/docs/modules/ROOT/templates/_rule_links.hbs
- antora/docs/modules/ROOT/templates/policy_configuration.hbs
- antora/ec-policies-antora-extension/index.js
In this patch I just added the list under the description and left them where they are in the docs. I think it's likely they'll be moved to a new location in the docs, but that can be done later.
> Document what rules are in each collection

- data/acceptable_tekton_bundles.yml
These were missed due to the know timinig issue.
https://issues.redhat.com/browse/HACBS-1709
> Add missing task-bundles to acceptable list

- antora/docs/modules/ROOT/templates/policy_configuration.hbs
- policy/release/attestation_task_bundle.rego
- policy/release/attestation_task_bundle_test.rego
- policy/release/attestation_type.rego
- policy/release/attestation_type_test.rego
- policy/release/base_image_registries.rego
- policy/release/base_image_registries_test.rego
- policy/release/slsa_provenance_available.rego
- policy/release/slsa_provenance_available_test.rego
- policy/release/slsa_source_version_controlled.rego
- policy/release/slsa_source_version_controlled_test.rego
- policy/release/step_image_registries.rego
- policy/release/step_image_registries_test.rego
- policy/release/tasks.rego
- policy/release/tasks_test.rego
[JIRA: HACBS-1615](https://issues.redhat.com/browse/HACBS-1615)
See commit messages for explanations.
> Introduce "minimal" collection

- policy/lib/result_helper.rego
- policy/lib/result_helper_test.rego
- policy/pipeline/required_tasks.rego
- policy/pipeline/required_tasks_test.rego
- policy/release/tasks.rego
- policy/release/tasks_test.rego
- policy/release/test.rego
- policy/release/test_test.rego
https://issues.redhat.com/browse/HACBS-1744
> Emit "term" for certain policy rules

- antora/docs/modules/ROOT/templates/policy_configuration.hbs
https://issues.redhat.com/browse/HACBS-1744
> Update docs for include/exclude with term

- data/acceptable_tekton_bundles.yml
This pr https://github.com/hacbs-contract/ec-cli/pull/394 updated the format
> update to reflect the new format

- hack/pr-infra-deployments.sh
> Fix policy source in infra-dep update

- antora/ec-policies-antora-extension/index.js
Some code changes were needed to handle the ESM `import`.
> Upgrade to latest (ESM) version of OPA inspect JS

- policy/lib/tekton/task_test.rego
- policy/release/hermetic_build_task.rego
- policy/release/hermetic_build_task_test.rego
The param name changed. Confirmed by Michal on slack.
> Change HERMETIC_BUILD param to HERMETIC

- data/rule_data.yml
https://issues.redhat.com/browse/STONEBLD-837
> Temporarily add cachi2 image location

- README.md
- antora/docs/modules/ROOT/pages/index.adoc
https://issues.redhat.com/browse/HACBS-1795
> Link to Stonesoup docs on GitHub pages

- policy/lib/rule_data.rego
- policy/release/cve.rego
- policy/release/cve_test.rego
https://issues.redhat.com/browse/HACBS-1671
> Add cve policy rules

- hack/update-infra-deployments.sh
https://issues.redhat.com/browse/HACBS-1822
> Update all ECP resources in infra-deployments

- data/rule_data.yml
https://issues.redhat.com/browse/HACBS-1948
> Add ART repo to list of allowed step images

- policy/pipeline/artifacthub-pkg.yml
- policy/release/artifacthub-pkg.yml
> Remove https in oci urls for artifacthub

- .github/workflows/docs.yaml
- Makefile
- README.md
- antora/docs/modules/ROOT/pages/authoring.adoc
- antora/docs/modules/ROOT/pages/index.adoc
- antora/docs/modules/ROOT/pages/policy_bundles.adoc
- antora/docs/modules/ROOT/templates/_rules.hbs
- antora/ec-policies-antora-extension/README.md
- antora/ec-policies-antora-extension/package.json
- data/rule_data.yml
- hack/validate-acceptable-bundles.sh
- policy/pipeline/artifacthub-pkg.yml
- policy/release/artifacthub-pkg.yml
https://issues.redhat.com/browse/HACBS-2004
> Update references to the new org

- antora/docs/modules/ROOT/templates/_rules.hbs
- antora/ec-policies-antora-extension/index.js
- policy/release/attestation_task_bundle.rego
- policy/release/cve.rego
I added one solution as a pilot just so we can see that it works. Adding solution text for other rules is still todo.
JIRA: [HACBS-2049](https://issues.redhat.com/browse/HACBS-2049)
> Show solution annotation in docs output

- antora/ec-policies-antora-extension/package-lock.json
- antora/ec-policies-antora-extension/package.json
This is part of renaming our npm org from hacbs-contract to enterprise-contract.
> UPDATE npm org to new value of enterprise-contract

- policy/lib/tekton/task.rego
- policy/lib/tekton/task_test.rego
- policy/release/provenance_materials.rego
- policy/release/provenance_materials_test.rego
https://issues.redhat.com/browse/HACBS-1302
> Add provenance_materials policy package

- antora/docs/modules/ROOT/pages/index.adoc
Updated the Title and definitions to align them better with the other guides.
> Updated the Title and definitions to align them better with the other guides.

- Makefile
- policy/build_task/labels.rego
- policy/lib/tekton/task.rego
- policy/release/lib/attestations_test.rego
Also fixes the unused parameters errors which are now reported.
> Upgrade OPA to v0.53.1

- policy/release/attestation_task_bundle.rego
- policy/release/attestation_type.rego
- policy/release/base_image_registries.rego
- policy/release/buildah_build_task.rego
- policy/release/cve.rego
- policy/release/hermetic_build_task.rego
- policy/release/java.rego
- policy/release/provenance_materials.rego
- policy/release/slsa_build_build_service.rego
- policy/release/slsa_build_scripted_build.rego
- policy/release/slsa_provenance_available.rego
- policy/release/slsa_source_version_controlled.rego
- policy/release/step_image_registries.rego
- policy/release/tasks.rego
- policy/release/test.rego
Ref. https://issues.redhat.com/browse/HACBS-2264
> Add `depends_on` annotations to release rules

- data/rule_data.yml
- policy/release/external_parameters.rego
- policy/release/external_parameters_test.rego
- policy/release/lib/attestations.rego
- policy/release/lib/attestations_test.rego
https://issues.redhat.com/browse/HACBS-2245
> Add policy to evaluate pipelinerun parameters

- checks/annotations.rego
- checks/annotations_test.rego
Ref. https://issues.redhat.com/browse/HACBS-2308
> Add `depends_on` annotation check

- Makefile
This should be useful for hacking on policies now that https://github.com/enterprise-contract/ec-cli/pull/821 is merged.
Currently it doesn't include the "signatures" key which shows up in the ec input. Not sure how to extract that easily.
> Extend make fetch-att to also fetch image data

- data/rule_data.yml
- policy/release/labels.rego
- policy/release/labels_test.rego
https://issues.redhat.com/browse/HACBS-2372
> Add labels policy rules

- policy/build_task/labels_test.rego
- policy/lib/assertions.rego
- policy/lib/assertions_test.rego
- policy/pipeline/basic_test.rego
- policy/pipeline/required_tasks_test.rego
- policy/pipeline/task_bundle_test.rego
- policy/release/attestation_task_bundle_test.rego
- policy/release/attestation_type_test.rego
- policy/release/base_image_registries_test.rego
- policy/release/buildah_build_task_test.rego
- policy/release/cve_test.rego
- policy/release/external_parameters_test.rego
- policy/release/github_certificate_test.rego
- policy/release/hermetic_build_task_test.rego
- policy/release/java_test.rego
- policy/release/labels_test.rego
- policy/release/provenance_materials_test.rego
- policy/release/slsa_build_build_service_test.rego
- policy/release/slsa_build_scripted_build_test.rego
- policy/release/slsa_provenance_available_test.rego
- policy/release/slsa_source_version_controlled_test.rego
- policy/release/step_image_registries_test.rego
- policy/release/tasks_test.rego
- policy/release/test_test.rego
- policy/task/kind_test.rego
https://issues.redhat.com/browse/HACBS-2374
> Ignore certain result attributes in unit tests

- policy/release/redhat_manifests.rego
- policy/release/redhat_manifests_test.rego
https://issues.redhat.com/browse/HACBS-2369
> Add Red Hat manifests policy

- checks/annotations_test.rego
- policy/build_task/labels.rego
- policy/build_task/labels_test.rego
- policy/pipeline/basic.rego
- policy/pipeline/basic_test.rego
- policy/pipeline/required_tasks.rego
- policy/pipeline/required_tasks_test.rego
- policy/pipeline/task_bundle.rego
- policy/release/attestation_task_bundle.rego
- policy/release/attestation_type.rego
- policy/release/base_image_registries.rego
- policy/release/buildah_build_task.rego
- policy/release/cve.rego
- policy/release/external_parameters.rego
- policy/release/github_certificate.rego
- policy/release/hermetic_build_task.rego
- policy/release/java.rego
- policy/release/labels.rego
- policy/release/olm.rego
- policy/release/provenance_materials.rego
- policy/release/slsa_build_build_service.rego
- policy/release/slsa_build_scripted_build.rego
- policy/release/slsa_provenance_available.rego
- policy/release/slsa_source_version_controlled.rego
- policy/release/step_image_registries.rego
- policy/release/tasks.rego
- policy/release/test.rego
- policy/task/kind.rego
- policy/task/kind_test.rego
[HACBS-2163](https://issues.redhat.com/browse/HACBS-2163)
> Rule description edits for consistency

- .github/workflows/push-bundles.yaml
- hack/update-bundles.sh
This will push the bundles to the new location in quay and keep the old location until references are updated.
https://issues.redhat.com/browse/HACBS-2047
> push quay bundles to enterprise-contract org

- checks/annotations.rego
- checks/annotations_test.rego
Make sure that the rule code is unique.
> Conventions check for duplicate rules

- policy/release/schedule.rego
- policy/release/schedule_test.rego
https://issues.redhat.com/browse/HACBS-2608
> Add schedule policy rules

- policy/release/tasks.rego
- policy/release/tasks_test.rego
https://issues.redhat.com/browse/RHTAPBUGS-799
> Add policy rule to check for failed tasks

- policy/lib/refs.rego
- policy/lib/refs_test.rego
- policy/lib/tekton/task.rego
- policy/lib/tekton/task_test.rego
- policy/release/buildah_build_task_test.rego
This is a follow-up to this https://github.com/enterprise-contract/ec-policies/pull/691. The task format is different than I expected. This PR fixes that mistake.
> Update the slsav1 task format

- policy/release/sbom_spdx.rego
- policy/release/sbom_spdx_test.rego
https://issues.redhat.com/browse/HACBS-2516
> Add sbom_spdx package

- .regal/config.yaml
- policy/lib/tekton/pipeline.rego
- policy/lib/tekton/pipeline_test.rego
- policy/lib/tekton/task.rego
- policy/release/lib/attestations.rego
- policy/release/tasks.rego
- policy/release/tasks_test.rego
This updates the time based required task list and the task status policies.
https://issues.redhat.com/browse/HACBS-2246
> Update tasks policy to include the slsav1 attestation format

- example/data/README.md
- example/data/acceptable_tekton_bundles.yml
- example/data/required_tasks.yml
- example/data/rule_data.yml
> Add example policy data

- policy/lib/rule_data.rego
- policy/release/cve.rego
- policy/release/cve_test.rego
> Add support for unpatched_vulnerabilities

- hack/update-infra-deployments.sh
This change fixes the update-infra-deployments.sh script so it doesn't crash if a certain YAML document is not an object, and avoids making changes to unrelated YAML files.
> Fix update-infra-deployments.sh

- policy/release/cve.rego
- policy/release/cve_test.rego
Quick patch to add support for the new `SCAN_OUTPUT` result name.
Resolves #769.
> Add support for SCAN_OUTPUT results

- policy/lib/rule_data.rego
- policy/release/olm.rego
- policy/release/olm_test.rego
Ref: https://issues.redhat.com/browse/EC-270
> Add policy rules for features annotations in OLM

- policy/release/olm.rego
- policy/release/olm_test.rego
> Verify CSV's spec.version format

- policy/release/slsa_build_scripted_build.rego
- policy/release/slsa_build_scripted_build_test.rego
> Verify image was produced by a trusted task

- policy/lib/tekton/pipeline.rego
- policy/lib/tekton/task.rego
- policy/lib/tekton/task_test.rego
- policy/pipeline/required_tasks.rego
- policy/pipeline/required_tasks_test.rego
- policy/release/tasks.rego
- policy/release/tasks_test.rego
https://issues.redhat.com/browse/RHTAPBUGS-1079
> if a future required task throws a warning, report the date when that task is required

- acceptance/acceptance_test.go
- acceptance/features/release.feature
This implements most of the feedback from https://github.com/enterprise-contract/ec-policies/pull/864
> Minor improvements to acceptance tests

- hack/update-infra-deployments.sh
The infra-deployments repo now contains ECP resources that use the task policy bundle. This commit teaches the update script to handle updating those references as well.
Ref: EC-358
> Also update ec-task-policy image ref

- policy/lib/bundles.rego
- policy/lib/time.rego
The _active_threshold computation was introduced to the package defined by bundles.rego. However, this is as generic function that can benefit any time-based computation. As such, this commit moves the function to time.rego, and also changes time.acceptable_items to use it.
> Move active threshold to time.rego

- antora/docs/modules/ROOT/attachments/acceptable_tekton_bundles.yml
- antora/docs/modules/ROOT/attachments/trusted_tekton_tasks.yml
`acceptable_tekton_bundles.yml` -> `trusted_tekton_tasks.yml`.
> Fixes the broken link in docs

- antora/docs/modules/ROOT/pages/trusting_bundles.adoc
Ref: https://issues.redhat.com/browse/EC-261
This is mostly a tidy version of the process outlined in that issue.
> Add documentation for customizing the list of acceptable Tasks

- policy/release/olm.rego
- policy/release/olm_test.rego
> Add rule to verify OLM subscriptions annotation

- policy/release/trusted_task.rego
With an `effective_on` of `2024-05-07T00:00:00Z` (Tuesday).
Reference: EC-388
> Add `release.trusted_task` to `redhat` collection

- antora/docs/modules/ROOT/pages/trusted_tasks.adoc
- policy/pipeline/required_tasks.rego
- policy/pipeline/task_bundle.rego
- policy/pipeline/task_bundle_test.rego
- policy/release/attestation_task_bundle.rego
- policy/release/attestation_task_bundle_test.rego
- policy/release/base_image_registries.rego
- policy/release/base_image_registries_test.rego
- policy/release/lib/attestations_test.rego
- policy/release/tasks.rego
- policy/release/tasks_test.rego
> Use Trusted task terminology

- .github/dependabot.yml
- .github/workflows/codeql.yml
- .github/workflows/docs.yaml
- .github/workflows/pre-merge-ci.yaml
- .github/workflows/push-bundles.yaml
- .github/workflows/release-antora-extension.yaml
- .github/workflows/scorecards.yml
- .regal/config.yaml
- Makefile
- acceptance/acceptance_test.go
- antora/docs/antora.yml
- antora/ec-policies-antora-extension/index.js
- example/data/required_tasks.yml
- example/data/rule_data.yml
- example/data/trusted_tekton_tasks.yml
- go.mod
- go.sum
- policy/artifacthub-repo.yml
- policy/pipeline/artifacthub-pkg.yml
- policy/release/artifacthub-pkg.yml
- tools.go
Copied over from ec-cli repository.
> Add license header lint

- policy/release/base_image_registries.rego
- policy/release/base_image_registries_test.rego
> Support reading base images from SBOM

- policy/release/test.rego
- policy/release/test_test.rego
Ref: https://issues.redhat.com/browse/EC-505
> Improve messages in the test package

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/release/tasks.rego
Document the pipeline-required-tasks and required-tasks keys and usage.
https://issues.redhat.com/browse/EC-71
> Clarifying required-tasks usage

- antora/docs/modules/ROOT/pages/trusting_tasks.adoc
Ref: https://issues.redhat.com/browse/EC-621
> Fix some misformatted trusting tasks docs

- Makefile
Optionally specify a git ref that will be used as the ec version for running the test suite using make.
This lets me confirm that v0.1-alpha is not compatible with the current latest policies and v0.2 is compatible[1].
```
EC_REF=release-v0.1-alpha make ec-version quiet-test #=> fails
EC_REF=release-v0.2 make ec-version quiet-test #=> passes
EC_REF=release-v0.4 make ec-version quiet-test #=> passes
```
You could use a specific git sha instead of a branch if you want to.
Ref: [EC-695](https://issues.redhat.com/browse/EC-695)
[1] ...probably. The test suite passes at least.
> Support using arbitrary & specific ec version

- policy/lib/tekton/task.rego
- policy/release/trusted_task.rego
- policy/release/trusted_task_test.rego
https://issues.redhat.com/browse/EC-696
> Rule to ensure test tasks use trusted artifacts

- policy/release/sbom_cyclonedx.rego
- policy/release/sbom_cyclonedx_test.rego
A small fixup for PR #1030
Ref: https://issues.redhat.com/browse/EC-638
> Fix typo in rule data attributes key

- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/partials/release_policy_nav.adoc
- policy/release/collection/rhtap-jenkins.rego
- policy/release/rhtap_jenkins.rego
Two fix-ups for recently merged #1091.
Ref: [EC-746](https://issues.redhat.com/browse/EC-746)
> RHTAP Jenkins collection followups

- README.md
- acceptance/samples/README.md
- acceptance/samples/policy-input-golden-container.json
- antora/docs/modules/ROOT/pages/index.adoc
- antora/docs/modules/ROOT/pages/trusting_tasks.adoc
- example/data/trusted_tekton_tasks.yml
- hack/refresh-examples.sh
This failed acceptance tests locally, but I thought I'd try it here anyway.
Ref: [EC-449](https://issues.redhat.com/browse/EC-449)
> Update some GitHub appstudio refs

- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/partials/release_policy_nav.adoc
- policy/release/buildah_build_task.rego
- policy/release/buildah_build_task_test.rego
> Disallow certain PLATFORM patterns

- Makefile
- antora/docs/modules/ROOT/pages/policy_bundles.adoc
- policy/release/cve.rego
Remove most of the references to the redhat-appstudio GitHub and Quay.io org as those are deprecated.
> Remove redhat-appstudio

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/release/labels.rego
- policy/release/labels_test.rego
> Add support for required label values

- antora/docs/modules/ROOT/pages/authoring.adoc
> Document pitfalls of writing policy rules

- policy/task/results.rego
- policy/task/results_test.rego
Often new Task versions will change the emitted results, this allows for an additional `version` qualifier to support that use case.
> Specific version support for required Task results

- .vscode/settings.json
- hack/ec-opa.sh
- hack/regal.sh
- regal.go
(see commit messages for more info)
> VS Code things

- acceptance/samples/policy-input-golden-container.json
- example/data/required_tasks.yml
- example/data/trusted_tekton_tasks.yml
Run `hack/refresh-examples.sh` and modified `example/data/required_tasks.yml` to remove the deprecated `sbom-json-check` Task.
> Refresh examples

- policy/lib/image.rego
- policy/lib/image_test.rego
- policy/release/olm.rego
- policy/release/olm_test.rego
> Exclude non-OCI refs from list of OLM image refs

- hack/update-infra-deployments.sh
> Update refs that may not have oci prefix

- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/partials/release_policy_nav.adoc
- policy/release/tasks.rego
- policy/release/tasks_test.rego
Including `pipeline-required-tasks`.
Ref: EC-323
> Add data validation to required-tasks data

- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/partials/release_policy_nav.adoc
- policy/lib/tekton/trusted.rego
- policy/lib/tekton/trusted_test.rego
- policy/release/trusted_task.rego
- policy/release/trusted_task_test.rego
> Verify trusted_tasks data

- policy/release/sbom_cyclonedx.rego
- policy/release/sbom_cyclonedx_test.rego
Ref: [KFLUXBUGS-1590](https://issues.redhat.com/browse/KFLUXBUGS-1590)
> Add terms to rules from sbom_cyclonedx package

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/release/base_image_registries.rego
- policy/release/base_image_registries_test.rego
> Allow base images from the snapshot

- hack/update-bundles.sh
Handles an error when `skopeo list-tags` fails, adds quotes around variables and the use of arrays when applicable.
> Cleanup the hack/update-bundles.sh script

- policy/lib/sbom/sbom.rego
- policy/lib/sbom/sbom_test.rego
> Ignore SBOM URLs for other images

- policy/release/lib/attestations.rego
- policy/release/lib/attestations_test.rego
- policy/release/rhtap_jenkins/rhtap_jenkins.rego
We'll soon be adding "github" and "gitlab" to the existing "jenkins" RHTAP CI support. This is a small step towards doing that.
Ref: https://issues.redhat.com/browse/EC-990
Ref: https://issues.redhat.com/browse/EC-991
> Small refactor in preparation for RHTAP multi-ci

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/lib/sbom/sbom.rego
- policy/lib/sbom/sbom_test.rego
- policy/release/sbom_cyclonedx/sbom_cyclonedx.rego
- policy/release/sbom_spdx/sbom_spdx.rego
> Remove support for SBOM from image

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/release/trusted_task/trusted_task.rego
Reference: https://issues.redhat.com/browse/EC-944
> Document the `task_expiry_warning_days` rule data

- policy/lib/image/image.rego
- policy/lib/image/image_test.rego
https://issues.redhat.com/browse/EC-1060
> Trim whitespace from image ref

- antora/docs/modules/ROOT/pages/task_policy.adoc
- policy/task/step_images/step_images.rego
Let's give us another month to make sure we address EC-1038.
> Bump effective_on of step_images_accessible

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/release/rpm_repos/rpm_repos.rego
- policy/release/rpm_repos/rpm_repos_test.rego
> Allow list of RPM repo IDs to be extended

- policy/release/base_image_registries/base_image_registries.rego
- policy/release/base_image_registries/base_image_registries_test.rego
EC adds support for SPDX format along side CycloneDX.
https://issues.redhat.com/browse/EC-882
> Support base images stored in SPDX format.

- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/partials/release_policy_nav.adoc
- policy/lib/sbom/sbom.rego
- policy/release/sbom_cyclonedx/sbom_cyclonedx.rego
- policy/release/sbom_spdx/sbom_spdx.rego
- policy/release/sbom_spdx/sbom_spdx_test.rego
https://issues.redhat.com/browse/EC-1022
> Add SPDX support for allowed_package_sources.

- .github/workflows/docs.yaml
- antora/docs/modules/ROOT/nav.adoc
- antora/docs/modules/ROOT/pages/index.adoc
- antora/docs/modules/ROOT/pages/pipeline_policy.adoc
- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/pages/trusted_tasks.adoc
- antora/docs/modules/ROOT/pages/trusting_tasks.adoc
- policy/pipeline/task_bundle/task_bundle.rego
- policy/release/attestation_task_bundle/attestation_task_bundle.rego
- policy/release/attestation_type/attestation_type.rego
- policy/release/tasks/tasks.rego
- policy/release/test/test.rego
Ref: [EC-1080](https://issues.redhat.com/browse/EC-1080)
> First Conforma rename

- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/partials/release_policy_nav.adoc
- policy/release/sbom_cyclonedx/sbom_cyclonedx.rego
- policy/release/sbom_spdx/sbom_spdx.rego
- policy/release/sbom_spdx/sbom_spdx_test.rego
Disallowed package attribute rule for spdx sboms.
https://issues.redhat.com/browse/EC-1102
> disallowed_package_attributes for spdx sbom

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/lib/tekton/trusted.rego
- policy/release/trusted_task/trusted_task.rego
- policy/release/trusted_task/trusted_task_test.rego
Also, add latest bundle ref to out of date task warning.
https://issues.redhat.com/browse/EC-1096
> Clarify out of date task warning

- policy/release/rpm_repos/rpm_repos.rego
- policy/release/rpm_repos/rpm_repos_test.rego
Following the example sbom - https://issues.redhat.com/secure/attachment/13343749/rh-syft.spdx.json
> Updating annotator type for cachi2

- README.md
- antora/docs/modules/ROOT/pages/release_policy.adoc
- antora/docs/modules/ROOT/partials/release_policy_nav.adoc
- policy/release/olm/olm.rego
- policy/release/olm/olm_test.rego
Reverts enterprise-contract/ec-policies#1251
> Revert "feat(ec-965): verify a set of pullspecs related to an image"

- antora/docs/modules/ROOT/pages/release_policy.adoc
- policy/release/olm/olm.rego
Adding inaccessible_related_images back to the
redhat collection after testing.
> Add inaccessible_related_images to collection

- policy/release/rhtap_multi_ci/rhtap_multi_ci.rego
- policy/release/rhtap_multi_ci/rhtap_multi_ci_test.rego
> Add support for Azure multi-ci RHTAP

- policy/release/rpm_pipeline/rpm_pipeline.rego
- policy/release/rpm_pipeline/rpm_pipeline_test.rego
> fix rpm pipeline

- renovate.json
https://issues.redhat.com/browse/EC-1143
> Basic renovate configuration

- acceptance/go.mod
Security updates are requiring > 1.23
> Upgrade go

- antora/docs/modules/ROOT/pages/packages/release_olm.adoc
- policy/lib/rule_data.rego
- policy/release/olm/olm.rego
- policy/release/olm/olm_test.rego
Should be merged after: https://github.com/release-engineering/rhtap-ec-policy/pull/147
> feat(CLOUDDST-27591): Update olm.allowed_registries to use new rule data
